---
description: 'FreeBSD 핸드북 용어집'
next: books/handbook/colophon
path: /books/handbook/
prev: books/handbook/pgpkeys
showBookMenu: 'true'
title: 'FreeBSD 용어집'
weight: 44
---

[glossary]
[[freebsd-glossary]]
= FreeBSD 용어집
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:!sectnums:
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/glossary/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

이 용어집에는 FreeBSD 커뮤니티와 문서에서 사용되는 용어와 약어가 포함되어 있습니다.

[discrete]
== A

ACL::
<<acl-glossary,Access Control List>> 참조.

ACPI::
<<acpi-glossary,Advanced Configuration and Power Interface>> 참조.

AMD::
<<amd-glossary,Automatic Mount Daemon>> 참조.

AML::
<<aml-glossary,ACPI Machine Language>> 참조.

API::
<<api-glossary,Application Programming Interface>> 참조.

APIC::
<<apic-glossary,Advanced Programmable Interrupt Controller>> 참조.

APM::
<<apm-glossary,Advanced Power Management>> 참조.

APOP::
<<apop-glossary,Authenticated Post Office Protocol>> 참조.

ASL::
<<asl-glossary,ACPI Source Language>> 참조.

ATA::
<<ata-glossary,Advanced Technology Attachment>> 참조.

ATM::
<<atm-glossary,Asynchronous Transfer Mode>> 참조.

[[aml-glossary]]
ACPI Machine Language::
ACPI 호환 운영 체제 내의 가상 머신에 의해 해석되는 의사 코드로, 기본 하드웨어와 OS에 제공되는 문서화된 인터페이스 사이에 계층을 제공합니다.

[[asl-glossary]]
ACPI Source Language::
프로그래밍 언어 AML로 작성됩니다.

[[acl-glossary]]
Access Control List::
일반적으로 파일 또는 네트워크 장치와 같은 개체에 연결된 권한 목록.

[[acpi-glossary]]
Advanced Configuration and Power Interface::
하드웨어가 운영 체제에 제공하는 인터페이스의 추상화를 제공하는 사양으로, 운영 체제가 기본 하드웨어에 대해 아무것도 몰라도 이를 최대한 활용할 수 있도록 합니다. ACPI는 이전에 APM, PNPBIOS 및 기타 기술에서 제공하던 기능을 발전시키고 대체하며 전력 소비, 머신 일시 중단, 디바이스 활성화 및 비활성화 등을 제어할 수 있는 기능을 제공합니다.

[[api-glossary]]
Application Programming Interface::
하나 이상의 프로그램 부분의 표준 상호 작용, 함께 작동하는 방법, 시기, 이유, 공유 또는 작동하는 데이터 등을 지정하는 절차, 프로토콜 및 도구의 집합.

[[apm-glossary]]
Advanced Power Management::
운영 체제가 BIOS와 함께 작동하여 전원 관리를 수행할 수 있도록 하는 API. APM은 대부분의 애플리케이션에서 훨씬 더 일반적이고 강력한 ACPI 사양으로 대체되었습니다.

[[apic-glossary]]
Advanced Programmable Interrupt Controller::
{empty}

[[ata-glossary]]
Advanced Technology Attachment::
{empty}

[[atm-glossary]]
Asynchronous Transfer Mode::
{empty}

[[apop-glossary]]
Authenticated Post Office Protocol::
{empty}

[[amd-glossary]]
Automatic Mount Daemon::
해당 파일 시스템 내의 파일 또는 디렉터리에 액세스할 때 자동으로 파일 시스템을 마운트하는 데몬.

[discrete]
== B

BAR::
<<bar-glossary,Base Address Register>> 참고.

BIND::
<<bind-glossary,Berkeley Internet Name Domain>> 참고.

BIOS::
<<bios-glossary,Basic Input/Output System>> 참고.

BSD::
<<bsd-glossary,Berkeley Software Distribution>> 참고.

[[bar-glossary]]
Base Address Register::
PCI 장치가 응답할 주소 범위를 결정하는 레지스터.

[[bios-glossary]]
Basic Input/Output System::
BIOS의 정의는 상황에 따라 약간 다릅니다. 어떤 사람들은 소프트웨어와 하드웨어 간의 인터페이스를 제공하기 위한 기본 루틴 세트가 있는 ROM 칩이라고 합니다. 다른 사람들은 시스템을 부트스트랩하는 데 도움이 되는 칩에 포함된 일련의 루틴이라고도 합니다. 부트스트래핑 프로세스를 구성하는 데 사용되는 화면이라고도 합니다. BIOS는 PC에 따라 다르지만 다른 시스템에도 비슷한 것이 있습니다.

[[bind-glossary]]
Berkeley Internet Name Domain::
DNS 프로토콜의 구현.

[[bsd-glossary]]
Berkeley Software Distribution::
이것은 link:http://www.berkeley.edu[The University of California at Berkeley]의 컴퓨터 시스템 연구 그룹(CSRG)이 AT&T의 32V UNIX(R)를 개선하고 수정할 때 붙인 이름입니다. FreeBSD는 CSRG 작업의 후손입니다.

[[bikeshed-glossary]]
Bikeshed Building::
복잡하지 않은 주제에 대해서는 많은 사람들이 의견을 제시하는 반면, 복잡한 주제에 대해서는 토론이 거의 또는 전혀 이루어지지 않는 현상. 이 용어의 유래는 extref:{faq}[FAQ, bikeshed-painting] 을 참조하세요.

[discrete]
== C

CD::
<<cd-glossary,Carrier Detect>> 참고.

CHAP::
<<chap-glossary,Challenge Handshake Authentication Protocol>> 참고.

CLIP::
<<clip-glossary,Classical IP over ATM>> 참고.

COFF::
<<coff-glossary,Common Object File Format>> 참고.

CPU::
<<cpu-glossary,Central Processing Unit>> 참고.

CTS::
<<cts-glossary,Clear To Send>> 참고.

[[cd-glossary]]
Carrier Detect::
캐리어가 감지되었음을 나타내는 RS232C 신호.

[[cpu-glossary]]
Central Processing Unit::
프로세서라고도 합니다. 모든 계산이 이루어지는 컴퓨터의 두뇌입니다. 다양한 명령어 집합을 가진 여러 가지 아키텍처가 있습니다. 가장 잘 알려진 아키텍처로는 Intel-x86 및 파생 아키텍처, Arm, PowerPC가 있습니다.

[[chap-glossary]]
Challenge Handshake Authentication Protocol::
클라이언트와 서버 간에 공유되는 패스워드를 기반으로 사용자를 인증하는 방법.

[[clip-glossary]]
Classical IP over ATM::
{empty}

[[cts-glossary]]
Clear To Send::
원격 시스템에 데이터 전송 권한을 부여하는 RS232C 신호.
+
<<rts-glossary,Also Request To Send>> 참고.

[[coff-glossary]]
Common Object File Format::
{empty}

[discrete]
== D

DAC::
<<dac-glossary,Discretionary Access Control>> 참고.

DDB::
<<ddb-glossary,Debugger>> 참고.

DES::
<<des-glossary,Data Encryption Standard>> 참고.

DHCP::
<<dhcp-glossary,Dynamic Host Configuration Protocol>> 참고.

DNS::
<<dns-glossary,Domain Name System>> 참고.

DSDT::
<<dsdt-glossary,Differentiated System Description Table>> 참고.

DSR::
<<dsr-glossary,Data Set Ready>> 참고.

DTR::
<<dtr-glossary,Data Terminal Ready>> 참고.

DVMRP::
<<dvmrp-glossary,Distance-Vector Multicast Routing Protocol>> 참고.

[[dac-glossary]]
Discretionary Access Control::
{empty}

[[des-glossary]]
Data Encryption Standard::
정보를 암호화하는 방법으로, 전통적으로 UNIX(R) 암호 및 man:crypt[3] 함수의 암호화 방법으로 사용되었습니다.

[[dsr-glossary]]
Data Set Ready::
모뎀에서 컴퓨터 또는 단말기로 전송되는 RS232C 신호로, 데이터를 송수신할 준비가 되었음을 나타냅니다.
+
<<dtr-glossary,Also Data Terminal Ready>> 참고.

[[dtr-glossary]]
Data Terminal Ready::
컴퓨터 또는 단말기에서 모뎀으로 전송되는 RS232C 신호로, 데이터를 송수신할 준비가 되었음을 나타냅니다.

[[ddb-glossary]]
Debugger::
시스템 상태를 검사하기 위한 대화형 in-kernel 기능으로, 시스템이 충돌한 후 장애와 관련된 이벤트를 확인하기 위해 자주 사용됩니다.

[[dsdt-glossary]]
Differentiated System Description Table::
기본 시스템에 대한 기본 구성 정보를 제공하는 ACPI 테이블.

[[dvmrp-glossary]]
Distance-Vector Multicast Routing Protocol::
{empty}

[[dns-glossary]]
Domain Name System::
사람이 읽을 수 있는 호스트 이름(예: mail.example.net)을 인터넷 주소로 변환하거나 그 반대로 변환하는 시스템.

[[dhcp-glossary]]
Dynamic Host Configuration Protocol::
컴퓨터(호스트)가 서버에 IP 주소를 요청할 때 동적으로 할당하는 프로토콜. 주소 할당을 "임대 (lease)"라고 합니다.

[discrete]
== E

ECOFF::
<<ecoff-glossary,Extended COFF>> 참고.

ELF::
<<elf-glossary,Executable and Linking Format>> 참고.

ESP::
<<esp-glossary,Encapsulated Security Payload>> 참고.

Encapsulated Security Payload::
{empty}

[[elf-glossary]]
Executable and Linking Format::
{empty}

[[ecoff-glossary]]
Extended COFF::
{empty}

[discrete]
== F

FADT::
<<fadt-glossary,Fixed ACPI Description Table>> 참고.

FAT::
<<fat-glossary,File Allocation Table>> 참고.

FAT16::
<<fat16-glossary,File Allocation Table (16-bit)>> 참고.

FTP::
<<ftp-glossary,File Transfer Protocol>> 참고.

[[fat-glossary]]
File Allocation Table::
{empty}

[[fat16-glossary]]
File Allocation Table (16-bit)::
{empty}

[[ftp-glossary]]
File Transfer Protocol::
TCP/IP 네트워크를 통해 파일을 전송하는 데 사용할 수 있는 TCP 위에 구현된 상위 수준 프로토콜 제품군의 구성원.

[[fadt-glossary]]
Fixed ACPI Description Table::
{empty}

[discrete]
== G

GUI::
<<gui-glossary,Graphical User Interface>> 참고.

[[giant-glossary]]
Giant::
대규모 커널 리소스 세트를 보호하는 상호 제외 메커니즘(절전 `mutex` )의 이름입니다. 머신에 수십 개의 프로세스와 하나의 네트워킹 카드, 그리고 단 하나의 프로세서만 있을 수 있는 시대에는 단순한 잠금 메커니즘으로 충분했지만, 오늘날에는 용납할 수 없는 성능 병목 현상이 발생하고 있습니다. FreeBSD 개발자들은 이를 개별 리소스를 보호하는 잠금으로 대체하기 위해 적극적으로 노력하고 있으며, 이는 단일 프로세서 및 다중 프로세서 머신 모두에서 훨씬 더 높은 수준의 병렬 처리를 가능하게 할 것입니다.

[[gui-glossary]]
Graphical User Interface::
사용자와 컴퓨터가 그래픽으로 상호 작용하는 시스템.

[discrete]
== H

HTML::
<<html-glossary,HyperText Markup Language>> 참고.

HUP::
<<hup-glossary,HangUp>> 참고.

[[hup-glossary]]
HangUp::
{empty}

[[html-glossary]]
HyperText Markup Language::
웹 페이지를 만드는 데 사용되는 마크업 언어.

[discrete]
== I

I/O::
<<io-glossary,Input/Output>> 참고.

IASL::
<<iasl-glossary,Intel’s ASL compiler>> 참고.

IMAP::
<<imap-glossary,Internet Message Access Protocol>> 참고.

IP::
<<ip-glossary,Internet Protocol>> 참고.

IPFW::
<<ipfw-glossary,IP Firewall>> 참고.

IPP::
<<ipp-glossary,Internet Printing Protocol>> 참고.

IPv4::
<<ipv4-glossary,IP Version 4>> 참고.

IPv6::
<<ipv6-glossary,IP Version 6>> 참고.

ISP::
<<isp-glossary,Internet Service Provider>> 참고.

[[ipfw-glossary]]
IP Firewall::
{empty}

[[ipv4-glossary]]
IP Version 4::
주소 지정에 32비트를 사용하는 IP 프로토콜 버전 4. 이 버전은 여전히 가장 널리 사용되고 있지만 서서히 IPv6로 대체되고 있습니다.
+
<<ipv6-glossary,Also IP Version 6>> 참고.

[[ipv6-glossary]]
IP Version 6::
새로운 IP 프로토콜. IPv4의 주소 공간이 부족하기 때문에 발명되었습니다. 주소 지정에 128비트를 사용합니다.

[[io-glossary]]
Input/Output::
{empty}

[[iasl-glossary]]
Intel’s ASL compiler::
ASL을 AML로 변환하기 위한 인텔의 컴파일러.

[[imap-glossary]]
Internet Message Access Protocol::
메일 서버에서 이메일 메시지에 액세스하기 위한 프로토콜로, 메시지가 일반적으로 메일 리더 클라이언트로 다운로드되는 대신 서버에 보관되는 것이 특징입니다.
+
Post Office Protocol Version 3 참고.

[[ipp-glossary]]
Internet Printing Protocol::
{empty}

[[ip-glossary]]
Internet Protocol::
인터넷의 기본 프로토콜인 패킷 전송 프로토콜입니다. 원래 미국 국방부에서 개발되었으며 TCP/IP 스택에서 매우 중요한 부분입니다. 인터넷 프로토콜이 없었다면 인터넷은 오늘날과 같은 모습을 갖추지 못했을 것입니다. 자세한 내용은 link:ftp://ftp.rfc-editor.org/in-notes/rfc791.txt[RFC 791] 을 참조하세요.

[[isp-glossary]]
Internet Service Provider::
인터넷에 대한 액세스를 제공하는 회사.

[discrete]
== K

[[kame-glossary]]
KAME::
"거북이"라는 뜻의 일본어인 KAME는 컴퓨팅 업계에서 IPv6 구현을 위해 노력하는 link:http://www.kame.net/[KAME Project] 를 지칭하는 용어로 사용됩니다.

KDC::
<<kdc-glossary,Key Distribution Center>> 참고.

KLD::
<<kld-glossary,Kernel ld(1)>> 참고.

KSE::
<<kse-glossary,Kernel Scheduler Entities>> 참고.

KVA::
<<kva-glossary,Kernel Virtual Address>> 참고.

Kbps::
<<kbps-glossary,Kilo Bits Per Second>> 참고.

[[kld-glossary]]
Kernel man:ld[1]::
시스템을 재부팅하지 않고 FreeBSD 커널에 기능을 동적으로 로드하는 방법.

[[kse-glossary]]
Kernel Scheduler Entities::
커널-지원 스레딩 시스템. link:http://www.freebsd.org/kse[project home page] 참조.

[[kva-glossary]]
Kernel Virtual Address::
{empty}

[[kdc-glossary]]
Key Distribution Center::
{empty}

[[kbps-glossary]]
Kilo Bits Per Second::
대역폭(지정된 시간 동안 특정 지점을 통과할 수 있는 데이터의 양)을 측정하는 데 사용됩니다. Kilo 접두사 대신 Mega, Giga, Tera 등을 사용할 수 있습니다.

[discrete]
== L

LAN::
<<lan-glossary,Local Area Network>> 참고.

LOR::
<<lor-glossary,Lock Order Reversal>> 참고.

LPD::
<<lpd-glossary,Line Printer Daemon>> 참고.

[[lpd-glossary]]
Line Printer Daemon::
{empty}

[[lan-glossary]]
Local Area Network::
사무실, 집 등과 같은 로컬 영역에서 사용되는 네트워크.

[[lor-glossary]]
Lock Order Reversal::
FreeBSD 커널은 여러 리소스 잠금을 사용하여 해당 리소스에 대한 경합을 중재합니다. FreeBSD-CURRENT 커널(릴리즈에서는 제거되었지만)에 있는 man:witness[4]라는 런타임 잠금 진단 시스템은 잠금 오류로 인한 교착 상태 가능성을 감지합니다. (man:witness[4]는 실제로 약간 보수적이기 때문에 False positive가 발생할 수 있습니다). True positive report는 "운이 나빴다면 여기서 교착 상태가 발생했을 것"이라는 것을 나타냅니다.
+
True positive LOR은 빠르게 수정되는 경향이 있으므로 메일링 리스트에 게시하기 전에 https://lists.FreeBSD.org/subscription/freebsd-current 및 link:http://sources.zabbadoz.net/freebsd/lor.html[LORs Seen] 페이지를 확인하세요.

[discrete]
== M

MAC::
<<mac-glossary,Mandatory Access Control>> 참고.

MADT::
<<madt-glossary,Multiple APIC Description Table>> 참고.

MFC::
<<mfc-glossary,Merge From Current>> 참고.

MFH::
<<mfh-glossary,Merge From Head>> 참고.

MFS::
<<mfs-glossary,Merge From Stable>> 참고.

MFV::
<<mfv-glossary,Merge From Vendor>> 참고.

MIT::
<<mit-glossary,Massachusetts Institute of Technology>> 참고.

MLS::
<<mls-glossary,Multi-Level Security>> 참고.

MOTD::
<<motd-glossary,Message Of The Day>> 참고.

MTA::
<<mta-glossary,Mail Transfer Agent>> 참고.

MUA::
<<mua-glossary,Mail User Agent>> 참고.

[[mta-glossary]]
Mail Transfer Agent::
이메일을 전송하는 데 사용되는 애플리케이션. MTA는 전통적으로 BSD 기본 시스템의 일부였습니다. 오늘날 Sendmail은 기본 시스템에 포함되어 있지만 postfix, qmail, Exim과 같은 다른 많은 MTA가 있습니다.

[[mua-glossary]]
Mail User Agent::
사용자가 이메일을 표시하고 작성하는 데 사용하는 애플리케이션.

[[mac-glossary]]
Mandatory Access Control::
{empty}

[[mit-glossary]]
Massachusetts Institute of Technology::
{empty}

[[mfc-glossary]]
Merge From Current::
현재 브랜치에서 다른 브랜치로 기능 또는 패치를 병합하려면 대부분 -STABLE을 사용합니다.

[[mfh-glossary]]
Merge From Head::
리포지토리 HEAD에서 이전 브랜치로 기능 또는 패치를 병합.

[[mfs-glossary]]
Merge From Stable::
일반적인 FreeBSD 개발 과정에서, 변경사항은 -CURRENT 브랜치에 커밋되어 테스트를 거친 후 -STABLE로 병합됩니다. 드물지만, 변경 사항이 -STABLE에 먼저 커밋된 후 -CURRENT로 병합되는 경우도 있습니다.
+
이 용어는 -STABLE에서 보안 브랜치로 패치를 병합할 때도 사용됩니다.
+
<<mfc-glossary,Also Merge From Current>> 참고.

[[mfv-glossary]]
Merge From Vendor::
{empty}

[[motd-glossary]]
Message Of The Day::
일반적으로 로그인 시 표시되는 메시지로, 시스템 사용자에게 정보를 배포하는 데 자주 사용됩니다.

[[mls-glossary]]
Multi-Level Security::
{empty}

[[madt-glossary]]
Multiple APIC Description Table::
{empty}

[discrete]
== N

NAT::
<<nat-glossary,Network Address Translation>> 참고.

NDISulator::
<<projectevil-glossary,Project Evil>> 참고.

NFS::
<<nfs-glossary,Network File System>> 참고.

NTFS::
<<ntfs-glossary,New Technology File System>> 참고.

NTP::
<<ntp-glossary,Network Time Protocol>> 참고.

[[nat-glossary]]
Network Address Translation::
게이트웨이를 통과하는 도중에 IP 패킷이 재작성되는 기술로, 게이트웨이 뒤에 있는 많은 컴퓨터가 단일 IP 주소를 효과적으로 공유할 수 있습니다.

[[nfs-glossary]]
Network File System::
{empty}

[[ntfs-glossary]]
New Technology File System::
Microsoft에서 개발한 파일 시스템으로, Windows(R) 2000, Windows NT(R) 및 Windows(R) XP와 같은 "New Technology" 운영 체제에서 사용할 수 있습니다.

[[ntp-glossary]]
Network Time Protocol::
네트워크를 통해 시계를 동기화하는 수단.

[discrete]
== O

OBE::
<<obe-glossary,Overtaken By Events>> 참고.

ODMR::
<<odmr-glossary,On-Demand Mail Relay>> 참고.

OS::
<<os-glossary,Operating System>> 참고.

[[odmr-glossary]]
On-Demand Mail Relay::
{empty}

[[os-glossary]]
Operating System::
컴퓨터의 하드웨어 리소스에 대한 액세스를 제공하는 프로그램, 라이브러리 및 도구의 집합입니다. 오늘날 운영 체제는 한 번에 하나의 프로그램만 실행하고 하나의 장치에만 액세스하는 단순한 설계부터 수천 명의 사용자에게 동시에 서비스를 제공할 수 있는 완전한 다중 사용자, 멀티태스킹 및 다중 프로세스 시스템까지 다양하며, 각 시스템은 수십 개의 서로 다른 애플리케이션을 실행합니다.

[[obe-glossary]]
Overtaken By Events::
FreeBSD의 이후 변경, 네트워킹 표준의 변경, 해당 하드웨어가 더 이상 사용되지 않는 등의 이유로 더 이상 관련성이 없거나 적용되지 않는 제안된 변경 사항(예: 문제 보고서 또는 기능 요청)을 표시합니다.

[discrete]
== P

PAE::
<<pae-glossary,Physical Address Extensions>> 참고.

PAM::
<<pam-glossary,Pluggable Authentication Modules>> 참고.

PAP::
<<pap-glossary,Password Authentication Protocol>> 참고.

PC::
<<pc-glossary,Personal Computer>> 참고.

PCNSFD::
<<pcnfsd-glossary,Personal Computer Network File System Daemon>> 참고.

PDF::
<<pdf-glossary,Portable Document Format>> 참고.

PID::
<<pid-glossary,Process ID>> 참고.

POLA::
<<pola-glossary,Principle Of Least Astonishment>> 참고.

POP::
<<pop-glossary,Post Office Protocol>> 참고.

POP3::
<<pop3-glossary,Post Office Protocol Version 3>> 참고.

PPD::
<<ppd-glossary,PostScript Printer Description>> 참고.

PPP::
<<ppp-glossary,Point-to-Point Protocol>> 참고.

PPPoA::
<<pppoa-glossary,PPP over ATM>> 참고.

PPPoE::
<<pppoe-glossary,PPP over Ethernet>> 참고.

[[pppoa-glossary]]
PPP over ATM::
{empty}

[[pppoe-glossary]]
PPP over Ethernet::
{empty}

PR::
<<pr-glossary,Problem Report>> 참고.

PXE::
<<pxe-glossary,Preboot eXecution Environment>> 참고.

[[pap-glossary]]
Password Authentication Protocol::
{empty}

[[pc-glossary]]
Personal Computer::
{empty}

[[pcnfsd-glossary]]
Personal Computer Network File System Daemon::
{empty}

[[pae-glossary]]
Physical Address Extensions::
물리적으로 32비트 폭의 주소 공간만 있는 시스템에서 최대 64GB의 RAM에 액세스할 수 있도록 하는 방법입니다(따라서 PAE를 사용하지 않으면 4GB로 제한됨).

[[pam-glossary]]
Pluggable Authentication Modules::
{empty}

[[ppp-glossary]]
Point-to-Point Protocol::
{empty}

[[pointyhat]]
Pointy Hat::
빌드를 망가뜨리거나, 리비전 번호를 거꾸로 만들거나, 소스 베이스에 다른 종류의 혼란을 야기하는 모든 FreeBSD 커미터에게 수여되는 던스 캡과 같은 신화적인 헤드기어입니다. 어떤 커미터라도 열심히 일하면 곧 많은 양을 모을 것입니다. 그 사용법은 (거의 항상?) 유머러스합니다.

[[pdf-glossary]]
Portable Document Format::
{empty}

[[pop-glossary]]
Post Office Protocol::
Post Office Protocol Version 3 참고.

[[pop3-glossary]]
Post Office Protocol Version 3::
메일 서버의 이메일 메시지에 액세스하기 위한 프로토콜로, 일반적으로 메시지가 서버에 남아 있지 않고 서버에서 클라이언트로 다운로드되는 것이 특징입니다.
+
<<imap-glossary,Also Internet Message Access Protocol>> 참고.

[[ppd-glossary]]
PostScript Printer Description::
{empty}

[[pxe-glossary]]
Preboot eXecution Environment::
{empty}

[[pola-glossary]]
Principle Of Least Astonishment::
FreeBSD가 발전함에 따라, 사용자가 볼 수 있는 변경 사항은 가능한 한 놀라서 당황하지 않게 유지되어야 합니다. 예를 들어, [.filename]#/etc/defaults/rc.conf# 에서 시스템 시작 변수를 임의로 재배열하는 것은 POLA를 위반하는 것입니다. 개발자는 사용자가 볼 수 있는 시스템 변경을 고려할 때 POLA를 고려합니다.

[[pr-glossary]]
Problem Report::
FreeBSD 소스나 문서에서 발견된 어떤 종류의 문제에 대한 설명입니다. extref:{problem-reports}[Writing FreeBSD Problem Reports] 를 참조하세요.

[[pid-glossary]]
Process ID::
시스템의 특정 프로세스에 고유한 번호로, 해당 프로세스를 식별하고 해당 프로세스에 대한 조치를 취할 수 있습니다.

[[projectevil-glossary]]
Project Evil::
빌 폴(Bill Paul)이 만든 NDISulator의 작업 제목으로, 그는 애초에 이런 것이 필요하다는 것이 (철학적 관점에서) 얼마나 끔찍한 일인지에 대해 언급하며 이름을 지었습니다. NDISulator는 Microsoft Windows(TM) NDIS 미니포트 네트워크 드라이버를 FreeBSD/i386에서 사용할 수 있도록 하는 특수 호환성 모듈입니다. 일반적으로 드라이버가 비공개 소스인 카드를 사용할 수 있는 유일한 방법입니다. [.filename]#src/sys/compat/ndis/subr_ndis.c# 을 참조하십시오.

[discrete]
== R

RA::
<<ra-glossary,Router Advertisement>> 참고.

RAID::
<<raid-glossary,Redundant Array of Inexpensive Disks>> 참고.

RAM::
<<ram-glossary,Random Access Memory>> 참고.

RD::
<<rd-glossary,Received Data>> 참고.

RFC::
<<rfc-glossary,Request For Comments>> 참고.

RISC::
<<risc-glossary,Reduced Instruction Set Computer>> 참고.

RPC::
<<rpc-glossary,Remote Procedure Call>> 참고.

RS232C::
<<rs232c-glossary,Recommended Standard 232C>> 참고.

RTS::
<<rts-glossary,Request To Send>> 참고.

[[ram-glossary]]
Random Access Memory::
{empty}

[[rcs-glossary]]
Revision Control System::
_RCS(Revision Control System)_ 는 일반 파일에 대한 “revision control”을 구현하는 가장 오래된 소프트웨어 제품군 중 하나입니다. 각 파일에 대한 여러 수정본을 저장, 검색, 보관, 로깅, 식별 및 병합할 수 있습니다. RCS는 함께 작동하는 여러 가지 작은 도구로 구성되어 있습니다. Git과 같은 최신 리비전 제어 시스템에서 볼 수 있는 일부 기능이 부족하지만, 설치, 구성 및 소규모 파일 집합에 사용하기 매우 간단합니다.
+
<<svn-glossary,Also Subversion>> 참고.

[[rd-glossary]]
Received Data::
데이터가 수신되는 RS232C 핀 또는 회선.
+
<<td-glossary,Also Transmitted Data>> 참고.

[[rs232c-glossary]]
Recommended Standard 232C::
직렬 장치 간 통신을 위한 표준.

[[risc-glossary]]
Reduced Instruction Set Computer::
하드웨어가 수행할 수 있는 연산을 단순화하되 가능한 한 범용적으로 만드는 프로세서 설계 방식. 이를 통해 전력 소비를 줄이고 트랜지스터 수를 줄이며 경우에 따라 더 나은 성능과 코드 밀도를 높일 수 있습니다. RISC 프로세서의 예로는 Alpha, SPARC(R), ARM(R), PowerPC(R) 등이 있습니다.

[[raid-glossary]]
Redundant Array of Inexpensive Disks::
{empty}

[[rpc-glossary]]
Remote Procedure Call::
{empty}

[[rfc-glossary]]
Request For Comments::
인터넷 표준, 프로토콜 등을 정의하는 일련의 문서. www.rfc-editor.org 참조.
+
누군가 변경 사항을 제안하고 피드백을 원할 때 일반적으로 사용되는 용어이기도 합니다.

[[rts-glossary]]
Request To Send::
원격 시스템에서 데이터 전송을 시작하도록 요청하는 RS232C 신호.
+
<<cts-glossary,Also Clear To Send>> 참고.

[[ra-glossary]]
Router Advertisement::
{empty}

[discrete]
== S

SCI::
<<sci-glossary,System Control Interrupt>> 참고.

SCSI::
<<scsi-glossary,Small Computer System Interface>> 참고.

SG::
<<sg-glossary,Signal Ground>> 참고.

SMB::
<<smb-glossary,Server Message Block>> 참고.

SMP::
<<smp-glossary,Symmetric MultiProcessor>> 참고.

SMTP::
<<smtp-glossary,Simple Mail Transfer Protocol>> 참고.

SMTP AUTH::
<<smtpauth-glossary,SMTP Authentication>> 참고.

SSH::
<<ssh-glossary,Secure Shell>> 참고.

STR::
<<str-glossary,Suspend To RAM>> 참고.

SVN::
<<svn-glossary,Subversion>> 참고.

[[smtpauth-glossary]]
SMTP Authentication::
{empty}

[[smb-glossary]]
Server Message Block::
{empty}

[[sg-glossary]]
Signal Ground::
신호의 접지 기준이 되는 RS232 핀 또는 와이어.

[[smtp-glossary]]
Simple Mail Transfer Protocol::
{empty}

[[ssh-glossary]]
Secure Shell::
{empty}

[[scsi-glossary]]
Small Computer System Interface::
{empty}

[[svn-glossary]]
Subversion::
Subversion은 현재 FreeBSD 프로젝트에서 사용하는 버전 관리 시스템입니다.

[[str-glossary]]
Suspend To RAM::
{empty}

[[smp-glossary]]
Symmetric MultiProcessor::
{empty}

[[sci-glossary]]
System Control Interrupt::
{empty}

[discrete]
== T

TCP::
<<tcp-glossary,Transmission Control Protocol>> 참고.

TCP/IP::
<<tcpip-glossary,Transmission Control Protocol/Internet Protocol>> 참고.

TD::
<<td-glossary,Transmitted Data>> 참고.

TFTP::
<<tftp-glossary,Trivial FTP>> 참고.

TGT::
<<tgt-glossary,Ticket-Granting Ticket>> 참고.

TSC::
<<tsc-glossary,Time Stamp Counter>> 참고.

[[tgt-glossary]]
Ticket-Granting Ticket::
{empty}

[[tsc-glossary]]
Time Stamp Counter::
최신 펜티엄(R) 프로세서에 내장된 프로파일링 카운터로 코어 주파수 클럭 틱을 계산합니다.

[[tcp-glossary]]
Transmission Control Protocol::
(예를 들어) IP 프로토콜 위에 위치하며 패킷이 안정적이고 정돈된 방식으로 전달되도록 보장하는 프로토콜.

[[tcpip-glossary]]
Transmission Control Protocol/Internet Protocol::
IP 프로토콜을 통해 실행되는 TCP 프로토콜의 조합을 나타내는 용어입니다. 인터넷의 대부분은 TCP/IP를 통해 실행됩니다.

[[td-glossary]]
Transmitted Data::
데이터가 전송되는 RS232C 핀 또는 와이어.
+
<<rd-glossary,Also Received Data>> 참고.

[[tftp-glossary]]
Trivial FTP::
{empty}

[discrete]
== U

UDP::
<<udp-glossary,User Datagram Protocol>> 참고.

UFS1::
<<ufs1-glossary,Unix File System Version 1>> 참고.

UFS2::
<<ufs2-glossary,Unix File System Version 2>> 참고.

UID::
<<uid-glossary,User ID>> 참고.

URL::
<<url-glossary,Uniform Resource Locator>> 참고.

USB::
<<usb-glossary,Universal Serial Bus>> 참고.

[[url-glossary]]
Uniform Resource Locator::
인터넷에서 문서와 같은 리소스를 찾는 방법과 해당 리소스를 식별하는 수단.

[[ufs1-glossary]]
Unix File System Version 1::
Berkeley Fast File System이라고도 하는 원래의 UNIX(R) 파일 시스템입니다.

[[ufs2-glossary]]
Unix File System Version 2::
FreeBSD 5-CURRENT에 도입된 UFS1의 확장. UFS2는 64비트 블록 포인터(1TB 장벽 깨기), 확장 파일 스토리지 지원 및 기타 기능을 추가했습니다.

[[usb-glossary]]
Universal Serial Bus::
다양한 컴퓨터 주변기기를 범용 인터페이스에 연결하는 데 사용되는 하드웨어 표준.

[[uid-glossary]]
User ID::
컴퓨터의 각 사용자에게 할당된 고유 번호로, 이를 통해 해당 사용자에게 할당된 리소스 및 권한을 식별할 수 있습니다.

[[udp-glossary]]
User Datagram Protocol::
TCP/IP 네트워크에서 데이터를 교환하는 데 사용되는 단순하고 신뢰하기는 어려운 데이터그램 프로토콜. UDP는 TCP처럼 오류 확인 및 수정 기능을 제공하지 않습니다.

[discrete]
== V

VPN::
<<vpn-glossary,Virtual Private Network>> 참고.

[[vpn-glossary]]
Virtual Private Network::
인터넷과 같은 공용 통신망을 사용하여 회사 LAN과 같은 로컬 네트워크에 원격 액세스를 제공하는 방법.
