---
description: 'freebsd-update 또는 Git을 사용하여 FreeBSD 시스템을 최신 상태로 유지하는 방법, 전체 기본 시스템을 다시 빌드하고 다시 설치하는 방법 등에 대한 정보입니다'
next: books/handbook/dtrace
part: '파트 III. 시스템 관리'
path: /books/handbook/
prev: books/handbook/l10n
showBookMenu: 'true'
tags: ["updating", "upgrading", "documentation", "FreeBSD-STABLE", "FreeBSD-CURRENT", "Security Patches"]
title: '25장. FreeBSD 업데이트 및 업그레이드하기'
weight: 29
---

[[updating-upgrading]]
= FreeBSD 업데이트 및 업그레이드하기
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 25
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/cutting-edge/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[updating-upgrading-synopsis]]
== 요약

FreeBSD는 릴리스 사이에 지속적인 개발이 이루어지고 있습니다. 어떤 사람들은 공식적으로 릴리즈된 버전을 선호하지만, 어떤 사람들은 최신 개발과 동기화되는 것을 선호합니다. 그러나 공식 릴리스조차도 종종 보안 및 기타 중요한 수정 사항으로 업데이트됩니다. 어떤 버전을 사용하든 FreeBSD는 시스템을 최신 상태로 유지하는 데 필요한 모든 도구를 제공하며, 버전 간에 쉽게 업그레이드할 수 있습니다. 이 장에서는 개발 시스템을 추적하는 방법과 FreeBSD 시스템을 최신 상태로 유지하기 위한 기본 도구에 대해 설명합니다.

이 장을 읽고 나면 다음을 알 수 있습니다:

* freebsd-update 또는 Git을 사용하여 FreeBSD 시스템을 최신 상태로 유지하는 방법.
* 설치된 시스템의 상태를 알려진 깨끗한 복사본과 비교하는 방법.
* Git 또는 문서 포트를 사용하여 설치된 문서를 최신 상태로 유지하는 방법.
* 두 개발 브랜치의 차이점: FreeBSD-STABLE과 FreeBSD-CURRENT.
* 전체 기본 시스템을 다시 빌드하고 다시 설치하는 방법.

이 챕터를 읽기 전에 알아두어야 할 사항입니다:

* 네트워크 연결을 올바르게 설정할 수 있습니다(crossref:advanced-networking[advanced-networking,Advanced Networking]).
* 타사 소프트웨어를 추가로 설치하는 방법을 알고 있습니다(crossref:ports[ports,Installing Applications: Packages and Ports]).

[NOTE]
====
이 장 전체에서 `git` 은 FreeBSD 소스를 얻고 업데이트하는 데 사용됩니다. 선택적으로 package:dev/git[] 포트 또는 패키지를 사용할 수 있습니다.
====

[[updating-upgrading-freebsdupdate]]
== FreeBSD 업데이트

보안 패치를 적시에 적용하고 운영 체제의 최신 릴리즈로 업그레이드하는 것은 지속적인 시스템 관리의 중요한 측면입니다. FreeBSD에는 이 두 가지 작업을 수행하는 데 사용할 수 있는 `freebsd-update` 라는 유틸리티가 포함되어 있습니다.

이 유틸리티는 패치나 새 커널을 수동으로 컴파일하고 설치할 필요 없이 FreeBSD에 대한 바이너리 보안 및 에라타 업데이트를 지원합니다. 바이너리 업데이트는 현재 보안 팀에서 지원하는 모든 아키텍처 및 릴리스에 사용할 수 있습니다. 지원되는 릴리스 목록과 예상 지원 종료 날짜는 https://www.FreeBSD.org/security/[https://www.FreeBSD.org/security/]에 나와 있습니다.

이 유틸리티는 마이너 포인트 릴리즈로의 운영 체제 업그레이드와 다른 릴리스 브랜치로의 업그레이드도 지원합니다. 새 릴리즈로 업그레이드하기 전에 해당 릴리스와 관련된 중요한 정보가 포함된 릴리스 공지를 검토하세요. 릴리스 공지는 https://www.FreeBSD.org/releases/[https://www.FreeBSD.org/releases/]에서 확인할 수 있습니다.

[NOTE]
====
man:crontab[5]의 기능을 사용하는 man:freebsd-update[8]가 있는 경우 운영 체제를 업그레이드하기 전에 비활성화해야 합니다.
====

이 섹션에서는 `freebsd-update` 에서 사용하는 구성 파일을 설명하고, 보안 패치를 적용하는 방법과 운영 체제 마이너 또는 메이저 릴리즈로 업그레이드하는 방법을 보여주며, 운영 체제를 업그레이드할 때 고려해야 할 몇 가지 사항에 대해 설명합니다.

[[freebsdupdate-config-file]]
=== 구성 파일

`freebsd-update` 의 기본 구성 파일은 그대로 작동합니다. 일부 사용자는 프로세스를 더 잘 제어할 수 있도록 [.filename]#/etc/freebsd-update.conf# 에서 기본 구성을 조정하고 싶을 수 있습니다. 이 파일의 주석에 사용 가능한 옵션이 설명되어 있지만 다음은 조금 더 설명이 필요할 수 있습니다:

[.programlisting]
....
# Components of the base system which should be kept updated.
Components world kernel
....

이 매개변수는 FreeBSD의 어떤 부분을 최신 상태로 유지할지 제어합니다. 기본값은 전체 기본 시스템과 커널을 업데이트하는 것입니다. 대신 `src/base` 또는 `src/sys` 와 같은 개별 구성 요소를 지정할 수 있습니다. 그러나 특정 항목을 포함하도록 변경하려면 필요한 모든 항목을 나열해야 하므로 기본값을 그대로 두는 것이 가장 좋습니다. 시간이 지나면 소스 코드와 바이너리가 동기화되지 않을 수 있으므로 재앙적인 결과를 초래할 수 있습니다.

[.programlisting]
....
# Paths which start with anything matching an entry in an IgnorePaths
# statement will be ignored.
IgnorePaths /boot/kernel/linker.hints
....

업데이트 프로세스 중에 [.filename]#/bin# 또는 [.filename]#/sbin# 과 같은 지정된 디렉터리를 그대로 유지하려면 이 문에 해당 경로를 추가합니다. 이 옵션은 `freebsd-update` 가 로컬 수정 사항을 덮어쓰는 것을 방지하는 데 사용할 수 있습니다.

[.programlisting]
....
# Paths which start with anything matching an entry in an UpdateIfUnmodified
# statement will only be updated if the contents of the file have not been
# modified by the user (unless changes are merged; see below).
UpdateIfUnmodified /etc/ /var/ /root/ /.cshrc /.profile
....

이 옵션은 지정된 디렉터리에 있는 수정되지 않은 구성 파일만 업데이트합니다. 사용자가 변경하면 이러한 파일이 자동으로 업데이트되지 않습니다. 병합 중에 변경 사항을 저장하도록 `freebsd-update` 에 지시하는 또 다른 옵션인 `KeepModifiedMetadata` 가 있습니다.

[.programlisting]
....
# When upgrading to a new FreeBSD release, files which match MergeChanges
# will have any local changes merged into the version from the new release.
MergeChanges /etc/ /var/named/etc/ /boot/device.hints
....

`freebsd-update` 가 병합을 시도할 구성 파일이 있는 디렉터리 목록입니다. 파일 병합 프로세스는 일련의 man:diff[1] 패치로 이루어지며, man:mergemaster[8]와 유사하지만 옵션이 더 적습니다. 병합이 수락되거나, 편집기를 열거나, `freebsd-update` 가 중단됩니다. 확실하지 않은 경우 [.filename]#/etc# 를 백업하고 병합을 수락합니다. `mergemaster` 에 대한 자세한 내용은 man:mergemaster[8]를 참조하십시오.

[.programlisting]
....
# Directory in which to store downloaded updates and temporary
# files used by FreeBSD Update.
# WorkDir /var/db/freebsd-update
....

이 디렉터리는 모든 패치와 임시 파일이 저장되는 곳입니다. 사용자가 버전 업그레이드를 수행하는 경우 이 위치에는 최소 기가바이트의 디스크 공간이 있어야 합니다.

[.programlisting]
....
# When upgrading between releases, should the list of Components be
# read strictly (StrictComponents yes) or merely as a list of components
# which *might* be installed of which FreeBSD Update should figure out
# which actually are installed and upgrade those (StrictComponents no)?
# StrictComponents no
....

이 옵션을 `yes` 로 설정하면 `freebsd-update` 는 `Components` 목록이 완전한 것으로 간주하고 목록 외부에서 변경을 시도하지 않습니다. 실제로 `freebsd-update` 는 `Components` 목록에 속하는 모든 파일을 업데이트하려고 시도합니다.

자세한 내용은 man:freebsd-update.conf[5]를 참조하세요.

[[freebsdupdate-security-patches]]
=== 보안 패치 적용하기

FreeBSD 보안 패치를 적용하는 프로세스가 간소화되어 관리자가 `freebsd-update` 를 사용하여 시스템을 완전히 패치된 상태로 유지할 수 있습니다. FreeBSD 보안 권고에 대한 자세한 정보는 crossref:security[security-advisories,"FreeBSD Security Advisories"]에서 확인할 수 있습니다.

FreeBSD 보안 패치는 다음 명령을 사용하여 다운로드하고 설치할 수 있습니다. 첫 번째 명령은 사용 가능한 패치가 있는지 확인하고, 있다면 패치가 적용될 경우 수정될 파일을 나열합니다. 두 번째 명령은 패치를 적용합니다.

[source, shell]
....
# freebsd-update fetch
# freebsd-update install
....

업데이트가 커널 패치를 적용하는 경우, 패치된 커널로 부팅하려면 시스템을 재부팅해야 합니다. 실행 중인 바이너리에 패치가 적용된 경우 영향을 받는 애플리케이션을 다시 시작하여 패치된 버전의 바이너리를 사용하도록 해야 합니다.

[NOTE]
====
일반적으로 사용자는 시스템을 재부팅할 준비가 되어 있어야 합니다. 커널 업데이트로 인해 시스템 재부팅이 필요한지 확인하려면 `freebsd-version -k` 및 `uname -r` 명령을 실행합니다. 출력이 다르면 시스템을 재부팅합니다.
====

이 항목을 [.filename]#/etc/crontab# 에 추가하여 매일 한 번씩 업데이트를 자동으로 확인하도록 시스템을 구성할 수 있습니다:

[.programlisting]
....
@daily                                  root    freebsd-update cron
....

패치가 있는 경우 자동으로 다운로드되지만 적용되지는 않습니다. `root` 사용자에게는 패치를 검토하고 `freebsd-update install` 을 사용하여 수동으로 설치할 수 있도록 이메일이 전송됩니다.

문제가 발생하면 `freebsd-update` 는 다음 명령으로 마지막 변경 사항을 롤백할 수 있습니다:

[source, shell]
....
# freebsd-update rollback
Uninstalling updates... done.
....

커널 또는 커널 모듈이 수정된 경우 시스템을 다시 시작하고 영향을 받는 바이너리를 모두 다시 시작해야 합니다.

[.filename]#GENERIC# 커널만 `freebsd-update` 로 자동 업데이트할 수 있습니다. 커스텀 커널을 설치한 경우, `freebsd-update` 가 업데이트 설치를 완료한 후 다시 빌드하고 다시 설치해야 합니다. 기본 커널 이름은 _GENERIC_ 입니다. man:uname[1] 명령을 사용하여 설치를 확인할 수 있습니다.

[NOTE]
====
항상 [.filename]#/boot/GENERIC# 에 [.filename]#GENERIC# 커널의 사본을 보관하세요. 다양한 문제를 진단하고 버전 업그레이드를 수행할 때 도움이 될 것입니다. [.filename]#GENERIC# 커널의 사본을 얻는 방법에 대한 지침은 <<freebsd-update-custom-kernel-9x>> 을 참조하세요.
====

[.filename]#/etc/freebsd-update.conf# 의 기본 구성이 변경되지 않은 경우, `freebsd-update` 는 나머지 업데이트와 함께 업데이트된 커널 소스를 설치합니다. 그런 다음 일반적인 방법으로 새 커스텀 커널을 재빌드하고 다시 설치할 수 있습니다.

`freebsd-update` 가 배포하는 업데이트에 항상 커널이 포함되는 것은 아닙니다. 커널 소스가 `freebsd-update install` 에 의해 수정되지 않은 경우 커스텀 커널을 다시 빌드할 필요는 없습니다. 그러나 `freebsd-update` 는 항상 [.filename]#/usr/src/sys/conf/newvers.sh# 을 업데이트합니다. `-p` 숫자로 표시된 현재 패치 레벨은 `uname -r` 로 확인할 수 있습니다. 커스텀 커널을 재빌드하면 다른 변경 사항이 없더라도 `uname` 이 시스템의 현재 패치 레벨을 정확하게 보고할 수 있습니다. 이 기능은 각 시스템에 설치된 업데이트를 빠르게 평가할 수 있으므로 여러 시스템을 유지 관리할 때 특히 유용합니다.

[[freebsdupdate-upgrade]]
=== 마이너 및 메이저 버전 업그레이드 수행하기

하나의 마이너 버전에서 다른 버전으로 업그레이드하는 것을 _마이너 버전_ 업그레이드라고 합니다. 예시입니다:

- FreeBSD 13.1 에서 13.2.

_메이저 버전_ 업그레이드는 메이저 버전 번호를 증가시킵니다. 예시입니다:

- FreeBSD 12.4 에서 13.2.

두 가지 유형의 업그레이드는 모두 릴리스 버전 대상과 함께 `freebsd-update` 를 제공하여 수행할 수 있습니다.

[WARNING]
====
새로운 `RELEASE` 가 발표될 때마다, FreeBSD 패키지 빌드 서버는 일정기간 동안 최신 버전의 운영 체제를 *사용하지* 않습니다. 이는 릴리스 발표 후 즉시 업그레이드하지 않는 많은 사용자들에게 연속성을 제공합니다. 예를 들어:

* 13.1 및 13.2 사용자를 위한 패키지는 13.1이 종료될 때까지 13.1을 실행하는 서버에 빌드되어 있습니다

-- 그리고 핵심적으로:

* 13.1에서 빌드된 커널 모듈이 13.2에 적합하지 *않을 수* 있습니다.

따라서 마이너 또는 메이저 OS 업그레이드 시 패키지 요구사항에 커널 모듈이 포함되어 있는 경우:

* *소스로부터 모듈을 빌드할 준비를 하세요*.

====

[NOTE]
====
시스템에서 커스텀 커널을 실행 중인 경우, 업그레이드를 시작하기 전에 [.filename]#GENERIC# 커널의 사본이 [.filename]#/boot/GENERIC# 에 있는지 확인합니다. [.filename]#GENERIC# 커널의 사본을 얻는 방법에 대한 지침은 <<freebsd-update-custom-kernel-9x>> 을 참조하십시오.
====

다음 명령은 FreeBSD 13.1 시스템에서 실행하면 FreeBSD 13.2로 업그레이드됩니다:

[source, shell]
....
# freebsd-update -r 13.2-RELEASE upgrade
....

명령이 수신되면 `freebsd-update` 는 업그레이드를 수행하는 데 필요한 정보를 수집하기 위해 구성 파일과 현재 시스템을 평가합니다. 화면 목록에 감지된 구성 요소와 감지되지 않은 구성 요소가 표시됩니다. 예를 들면 다음과 같습니다:

[source, shell]
....
Looking up update.FreeBSD.org mirrors... 1 mirrors found.
Fetching metadata signature for 13.1-RELEASE from update1.FreeBSD.org... done.
Fetching metadata index... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
kernel/smp src/base src/bin src/contrib src/crypto src/etc src/games
src/gnu src/include src/krb5 src/lib src/libexec src/release src/rescue
src/sbin src/secure src/share src/sys src/tools src/ubin src/usbin
world/base world/info world/lib32 world/manpages

The following components of FreeBSD do not seem to be installed:
kernel/generic world/catpages world/dict world/doc world/games
world/proflibs

Does this look reasonable (y/n)? y
....

이 시점에서 `freebsd-update` 는 업그레이드에 필요한 모든 파일을 다운로드하려고 시도합니다. 경우에 따라 사용자에게 무엇을 설치해야 하는지 또는 어떻게 진행해야 하는지 묻는 메시지가 표시될 수 있습니다.

사용자 정의 커널을 사용하는 경우 위 단계를 수행하면 다음과 유사한 경고가 표시됩니다:

[source, shell]
....
WARNING: This system is running a "MYKERNEL" kernel, which is not a
kernel configuration distributed as part of FreeBSD 13.1-RELEASE.
This kernel will not be updated: you MUST update the kernel manually
before running "/usr/sbin/freebsd-update install"
....

이 경고는 현재로서는 무시해도 됩니다. 업데이트된 [.filename]#GENERIC# 커널은 업그레이드 프로세스의 중간 단계로 사용됩니다.

모든 패치가 로컬 시스템에 다운로드되면 패치가 적용됩니다. 이 과정은 컴퓨터의 속도와 워크로드에 따라 다소 시간이 걸릴 수 있습니다. 그런 다음 구성 파일이 병합됩니다. 병합 프로세스에는 파일이 병합되거나 수동 병합을 위한 편집기가 화면에 표시될 수 있으므로 약간의 사용자 개입이 필요합니다. 병합이 성공할 때마다 프로세스가 계속 진행됨에 따라 병합 결과가 사용자에게 표시됩니다. 병합이 실패하거나 무시되면 프로세스가 중단됩니다. 사용자는 [.filename]#/etc# 를 백업해 두었다가 나중에 [.filename]#master.passwd# 또는 [.filename]#group# 과 같은 중요한 파일을 수동으로 병합할 수 있습니다.

[NOTE]
====
모든 패치와 병합이 다른 디렉토리에서 이루어지고 있기 때문에 시스템은 아직 변경되지 않습니다. 모든 패치가 성공적으로 적용되고 모든 구성 파일이 병합되어 프로세스가 순조롭게 진행되면 사용자가 다음 명령을 사용하여 변경 사항을 디스크에 커밋할 수 있습니다:

[source, shell]
....
# freebsd-update install
....

====

커널과 커널 모듈이 먼저 패치됩니다. 시스템이 사용자 지정 커널로 실행 중인 경우 man:nextboot[8]를 사용하여 다음 부팅 시 커널을 업데이트된 [.filename]#/boot/GENERIC# 으로 설정합니다:

[source, shell]
....
# nextboot -k GENERIC
....

[WARNING]
====
[.filename]#GENERIC# 커널로 재부팅하기 전에 업데이트 중인 머신이 원격으로 액세스되는 경우 시스템이 제대로 부팅되고 네트워크에 연결되는 데 필요한 모든 드라이버가 포함되어 있는지 확인하세요. 특히 실행 중인 커스텀 커널에 일반적으로 커널 모듈에서 제공하는 기본 제공 기능이 포함되어 있는 경우 [.filename]#/boot/loader.conf# 기능을 사용하여 이 모듈을 [.filename]#GENERIC# 커널에 임시로 로드해야 합니다. 업그레이드 프로세스가 완료될 때까지 필수적이지 않은 서비스는 물론 디스크 및 네트워크 마운트도 비활성화하는 것이 좋습니다.
====

이제 컴퓨터가 업데이트된 커널로 재시작합니다:

[source, shell]
....
# shutdown -r now
....

시스템이 다시 온라인 상태가 되면 다음 명령을 사용하여 `freebsd-update` 를 다시 시작합니다. 프로세스 상태가 저장되었으므로 `freebsd-update` 는 처음부터 시작하지 않고 다음 단계로 이동하여 이전 공유 라이브러리와 오브젝트 파일을 모두 제거합니다.

[source, shell]
....
# freebsd-update install
....

[NOTE]
====
라이브러리 버전 번호가 변경되었는지 여부에 따라 설치 단계가 세 단계가 아닌 두 단계만 있을 수 있습니다.
====

이제 업그레이드가 완료되었습니다. 메이저 버전 업그레이드인 경우, <<freebsdupdate-portsrebuild>> 에 설명된 대로 모든 포트와 패키지를 다시 설치하세요.

[[freebsd-update-custom-kernel-9x]]
==== FreeBSD 9.X 이상의 커스텀 커널

`freebsd-update` 를 사용하기 전에 [.filename]#/boot/GENERIC# 에 [.filename]##GENERIC# 커널의 사본이 있는지 확인하십시오. 커스텀 커널이 한 번만 빌드된 경우, [.filename]#/boot/kernel.old# 의 커널은 `GENERIC` 커널입니다. 이 디렉터리의 이름을 [.filename]#/boot/GENERIC# 으로 변경하기만 하면 됩니다.

사용자 지정 커널이 두 번 이상 빌드되었거나 사용자 지정 커널이 빌드된 횟수를 알 수 없는 경우, 운영 체제의 현재 버전과 일치하는 `GENERIC` 커널의 사본을 가져옵니다. 시스템에 물리적으로 액세스할 수 있는 경우 설치 미디어에서 `GENERIC` 커널의 사본을 설치할 수 있습니다:

[source, shell]
....
# mount /cdrom
# cd /cdrom/usr/freebsd-dist
# tar -C/ -xvf kernel.txz boot/kernel/kernel
....

대신에 `GENERIC` 커널을 소스에서 다시 빌드하여 설치할 수도 있습니다:

[source, shell]
....
# cd /usr/src
# make kernel __MAKE_CONF=/dev/null SRCCONF=/dev/null
....

이 커널이 `freebsd-update` 에 의해 `GENERIC` 커널로 식별되려면 [.filename]#GENERIC# 구성 파일이 어떤 식으로든 수정되지 않아야 합니다. 또한 커널은 다른 특별한 옵션 없이 빌드하는 것이 좋습니다.

[.filename]#GENERIC# 커널로 재부팅할 필요는 없으며, `freebsd-update` 는 [.filename]#/boot/GENERIC# 이 존재하기만 하면 됩니다.

[[freebsdupdate-portsrebuild]]
==== 메이저 버전 업그레이드 후 패키지 업그레이드하기

일반적으로 설치된 애플리케이션은 마이너 버전 업그레이드 후에도 문제 없이 계속 작동합니다. 메이저 버전은 다른 ABI(애플리케이션 바이너리 인터페이스)를 사용하므로 대부분의 타사 애플리케이션이 중단됩니다. 메이저 버전 업그레이드 후에는 설치된 모든 패키지와 포트를 업그레이드해야 합니다. 패키지는 `pkg upgrade` 를 사용하여 업그레이드할 수 있습니다. 설치된 포트를 업그레이드하려면 package:ports-mgmt/portmaster[] 같은 유틸리티를 사용하세요.

설치된 모든 패키지를 강제 업그레이드하면 버전 번호가 증가하지 않더라도 저장소의 새 버전으로 패키지가 교체됩니다. 이는 FreeBSD의 주요 버전 간에 업그레이드할 때 ABI 버전 변경 때문에 필요합니다. 강제 업그레이드는 다음을 수행하여 수행할 수 있습니다:

[source, shell]
....
# pkg-static upgrade -f
....

이 명령으로 설치된 모든 애플리케이션을 다시 빌드할 수 있습니다:

[source, shell]
....
# portmaster -af
....

이 명령은 구성 가능한 옵션이 있는 각 애플리케이션에 대한 구성 화면을 표시하고 사용자가 해당 화면과 상호 작용할 때까지 기다립니다. 이 동작을 방지하고 기본 옵션만 사용하려면 위 명령에 `-G` 를 포함하세요.

소프트웨어 업그레이드가 완료되면 `freebsd-update` 를 마지막으로 호출하여 업그레이드 프로세스를 완료하고 업그레이드 프로세스의 모든 느슨한 끝을 마무리합니다:

[source, shell]
....
# freebsd-update install
....

만약 [.filename]#GENERIC# 커널을 임시로 사용했다면, 이제 crossref:kernelconfig[kernelconfig,Configuring the FreeBSD Kernel]의 지침에 따라 새로운 커스텀 커널을 빌드하고 설치해야 합니다.

컴퓨터를 새 FreeBSD 버전으로 재부팅합니다. 이제 업그레이드 프로세스가 완료되었습니다.

[[freebsdupdate-system-comparison]]
=== 시스템 상태 비교

알려진 정상 복사본과 비교하여 설치된 FreeBSD 버전의 상태는 `freebsd-update IDS` 를 사용하여 테스트할 수 있습니다. 이 명령은 시스템 유틸리티, 라이브러리 및 구성 파일의 현재 버전을 평가하며 내장된 침입 탐지 시스템(IDS)으로 사용할 수 있습니다.

[WARNING]
====
이 명령은 package:security/snort[] 같은 실제 IDS를 대체할 수 없습니다. `freebsd-update` 는 디스크에 데이터를 저장하기 때문에 변조 가능성이 분명히 존재합니다. `kern.securelevel` 을 사용하며 사용하지 않을 때 `freebsd-update` 데이터를 읽기 전용 파일 시스템에 저장하면 이러한 가능성을 줄일 수 있지만, 더 나은 해결책은 시스템을 DVD 또는 안전하게 저장된 외부 USB 디스크 장치와 같은 보안 디스크와 비교하는 것입니다. 내장 유틸리티를 사용하여 IDS 기능을 제공하는 다른 방법은 crossref:security[security-ids,"Binary Verification"]에 설명되어 있습니다
====

비교를 시작하려면 결과를 저장할 출력 파일을 지정합니다:

[source, shell]
....
# freebsd-update IDS >> outfile.ids
....

이제 시스템을 검사하고 릴리스에서 알려진 값과 현재 설치에 대한 SHA256 해시 값과 함께 긴 파일 목록이 지정된 출력 파일로 전송됩니다.

목록의 항목은 매우 길지만 출력 형식은 쉽게 파악할 수 있습니다. 예를 들어 릴리스에 포함된 파일과 다른 모든 파일 목록을 가져오려면 다음 명령을 실행합니다:

[source, shell]
....
# cat outfile.ids | awk '{ print $1 }' | more
/etc/master.passwd
/etc/motd
/etc/passwd
/etc/pf.conf
....

이 샘플 출력은 더 많은 파일이 존재하므로 잘라낸 것입니다. 일부 파일에는 자연스러운 수정이 있습니다. 예를 들어, 사용자가 시스템에 추가된 경우 [.filename]#/etc/passwd# 가 수정됩니다. 커널 모듈은 `freebsd-update` 가 업데이트했을 수 있으므로 다를 수 있습니다. 특정 파일이나 디렉토리를 제외하려면 [.filename]#/etc/freebsd-update.conf# 에 `IDSIgnorePaths` 옵션을 추가합니다.

[[updating-bootcode]]
== 부트코드 업데이트하기

다음 매뉴얼은 부트코드 및 부트 로더의 업그레이드 프로세스를 설명합니다: man:gpart[8], man:gptboot[8], man:gptzfsboot[8], man:loader.efi[8].

[[updating-upgrading-documentation]]
== 문서 세트 업데이트하기

문서는 FreeBSD 운영 체제의 필수적인 부분입니다. FreeBSD 웹 사이트(link:https://docs.FreeBSD.org[Documentation Portal])에서 항상 최신 버전의 FreeBSD 문서를 이용할 수 있지만, FreeBSD 웹사이트, 핸드북, FAQ 및 기사의 최신 로컬 사본을 가지고 있으면 편리할 수 있습니다.

이 섹션에서는 소스 또는 FreeBSD 포트 컬렉션을 사용하여 FreeBSD 문서의 로컬 사본을 최신 상태로 유지하는 방법을 설명합니다.

문서 편집 및 수정본 제출에 대한 자세한 내용은 신규 기여자를 위한 FreeBSD 문서 프로젝트 입문서(extref:{fdp-primer}[FreeBSD Documentation Project Primer for New Contributors])를 참고하세요.

[[updating-installed-documentation]]
=== 소스에서 문서 업데이트하기

소스에서 FreeBSD 문서를 리빌드하려면 FreeBSD 기본 시스템에 포함되지 않은 도구 모음이 필요합니다. 필요한 도구는 FreeBSD 문서 프로젝트 입문서에서 extref:{fdp-primer}[these steps, overview-quick-start]에 따라 설치할 수 있습니다.

설치가 완료되면 `git` 을 사용하여 문서 소스의 깨끗한 복사본을 가져옵니다:

[source, shell]
....
# git clone https://git.FreeBSD.org/doc.git /usr/doc
....

문서 소스를 처음 다운로드할때는 시간이 걸릴 수 있습니다. 완료될 때까지 기다리세요.

문서 소스의 향후 업데이트는 다음을 실행하여 가져올 수 있습니다:

[source, shell]
....
# git pull
....

문서 소스의 최신 스냅샷을 [.filename]#/usr/doc# 으로 가져오면 설치된 문서를 업데이트할 준비가 완료된 것입니다.

전체 업데이트는 다음을 입력하여 진행할 수 있습니다:

[source, shell]
....
# cd /usr/doc
# make
....

[[current-stable]]
== 개발 브랜치 추적하기

FreeBSD에는 두 가지 개발 브랜치가 있습니다: FreeBSD-CURRENT와 FreeBSD-STABLE입니다.

이 섹션에서는 각 브랜치 및 해당 대상에 대한 설명과 각 브랜치에서 시스템을 최신 상태로 유지하는 방법에 대해 설명합니다.

[[current]]
=== FreeBSD-CURRENT 사용하기

FreeBSD-CURRENT는 FreeBSD 개발의 "최첨단"이며, FreeBSD-CURRENT 사용자는 높은 수준의 기술을 가지고 있을 것으로 예상합니다. 개발 브랜치를 추적하고자 하는 기술 수준이 낮은 사용자는 FreeBSD-STABLE을 대신 추적해야 합니다.

FreeBSD-CURRENT는 FreeBSD의 최신 소스 코드이며, 진행 중인 작업, 실험적인 변경 사항, 다음 공식 릴리스에 포함될 수도 있고 포함되지 않을 수도 있는 과도기적 메커니즘이 포함되어 있습니다. 많은 FreeBSD 개발자들이 매일 FreeBSD-CURRENT 소스 코드를 컴파일하지만, 짧은 기간 동안 소스를 빌드할 수 없는 경우가 있습니다. 이러한 문제는 가능한 한 빨리 해결되지만, FreeBSD-CURRENT가 재앙이 될지 아니면 새로운 기능이 될지는 소스 코드가 언제 동기화되었는지에 따라 달라질 수 있습니다.

FreeBSD-CURRENT는 세 가지 주요 관심 그룹을 위해 제공됩니다:

. 소스 트리의 일부에서 적극적으로 작업하고 있는 FreeBSD 커뮤니티 구성원.
. 적극적인 테스터로 활동하는 FreeBSD 커뮤니티 구성원. 이들은 기꺼이 시간을 내어 문제를 해결하고, 변경 사항과 FreeBSD의 전반적인 방향에 대해 제안하고, 패치를 제출합니다.
. 상황을 계속 주시하거나, 참고용으로 현재 소스를 사용하거나, 가끔 댓글이나 코드 기여를 하고자 하는 사용자.

프리 릴리즈 기능은 아직 완전히 테스트되지 않았고 버그를 포함하고 있을 가능성이 높기 때문에 FreeBSD-CURRENT를 다음 릴리즈 전에 새로운 기능을 얻는 빠른 경로로 간주해서는 _안됩니다_ . 특정 커밋은 기존 버그를 수정하는 것만큼이나 새로운 버그를 도입할 가능성이 높기 때문에 버그 수정을 빠르게 얻을 수 있는 방법이 아닙니다. FreeBSD-CURRENT는 어떤 형태의 "공식적인 지원"도 없습니다.

FreeBSD-CURRENT를 추적하려면:

. {freebsd-current} 및 {dev-commits-src-main} 목록에 가입하세요. 이것은 시스템의 현재 상태에 대한 사람들의 의견을 보고 FreeBSD-CURRENT의 현재 상태에 대한 중요한 게시물을 받기 위해 _반드시_ 필요합니다.
+
{dev-commits-src-main} 목록에는 변경이 이루어질 때마다 커밋 로그 항목이 유발할 수 있는 문제에 대한 관련 정보가 함께 기록됩니다.
+
이 목록에 가입하려면 {mailing-lists}로 이동하여 구독할 목록을 클릭하고 지침을 따르세요. FreeBSD-CURRENT에 대한 변경 사항뿐만 아니라 전체 소스 트리의 변경 사항을 추적하려면 {dev-commits-src-all}을 구독하세요.
. FreeBSD-CURRENT 소스와 동기화합니다. 일반적으로 `git` 은 FreeBSD Git 저장소의 `main` 브랜치에서 -CURRENT 코드를 체크아웃하는 데 사용됩니다(자세한 내용은 crossref:mirrors[git,“Using Git”]을 참조하세요).
. 저장소의 크기 때문에, 일부 사용자는 관심 있거나 패치에 기여하고 있는 소스 섹션만 동기화하도록 선택할 수 있습니다. 그러나 소스에서 운영체제를 컴파일하려는 사용자는 선택한 부분뿐만 아니라 FreeBSD-CURRENT의 _모든_ 부분을 다운로드해야 합니다.
+
FreeBSD-CURRENT를 컴파일하기 전에 [.filename]#/usr/src/Makefile# 을 주의 깊게 읽고 <<makeworld>> 에 있는 지침을 따르세요. 다음 릴리즈로 가는 과정에서 때때로 필요한 부트스트랩 절차에 대한 최신 정보를 얻으려면 {freebsd-current} 및 [.filename]#/usr/src/UPDATING# 을 읽으세요.
. 적극적으로 참여하세요! FreeBSD-CURRENT 사용자는 개선 사항이나 버그 수정에 대한 제안을 제출할 것을 권장합니다. 코드가 첨부된 제안은 언제나 환영합니다.

[[stable]]
=== FreeBSD-STABLE 사용하기

FreeBSD-STABLE은 주요 릴리스가 만들어지는 개발 브랜치입니다. 변경 사항은 느린 속도로 이 브랜치에 적용되며, 일반적으로 FreeBSD-CURRENT에서 먼저 테스트를 거쳤다고 가정합니다. 이것 역시 _아직_ 개발 브랜치이며, FreeBSD-STABLE의 소스가 일반적인 사용에 적합할 수도 있고 적합하지 않을 수도 있습니다. 이 브랜치는 최종 사용자를 위한 리소스가 아닌 또 다른 엔지니어링 개발 트랙일 뿐입니다. 테스트를 수행할 수 있는 리소스가 없는 사용자는 대신 가장 최신 버전의 FreeBSD를 실행해야 합니다.

FreeBSD 개발 과정을 추적하거나 기여하는 데 관심이 있으신 분들, 특히 FreeBSD의 다음 릴리즈와 관련하여 관심이 있으신 분들은 FreeBSD-STABLE을 팔로우하는 것을 고려해 보시기 바랍니다.

FreeBSD-STABLE 브랜치는 항상 컴파일후에 실행해야 하지만, 안전성을 보장할 수는 없습니다. FreeBSD-CURRENT보다 더 많은 사람들이 FreeBSD-STABLE을 실행하기 때문에, FreeBSD-CURRENT에서는 발견되지 않았던 버그와 코너 케이스가 FreeBSD-STABLE에서 발견되는 것은 불가피한 일입니다. 그렇기 때문에 무턱대고 FreeBSD-STABLE을 추적해서는 안됩니다. 특히 개발 또는 테스트 환경에서 코드를 철저히 테스트하지 않고 프로덕션 서버를 FreeBSD-STABLE로 _업데이트하지 않는 것_ 이 중요합니다.

FreeBSD-STABLE을 추적하려면:

. FreeBSD-STABLE에 나타날 수 있는 빌드 종속성이나 특별한 주의가 필요한 기타 문제에 대한 정보를 얻으려면 {freebsd-stable}에 가입하세요. 또한 개발자는 논란의 여지가 있는 수정이나 업데이트를 고려할 때 이 메일링 리스트에 공지하여 사용자가 제안한 변경 사항에 대해 제기할 문제가 있는 경우 응답할 수 있는 기회를 제공합니다.
+
추적 중인 브랜치에 대한 관련 깃 목록에 참여합니다. 예를 들어 {betarel-current-major}-STABLE 브랜치를 추적하는 사용자는 {dev-commits-src-branches}에 가입해야 합니다. 이 목록은 변경이 이루어질 때마다 커밋 로그 항목과 함께 가능한 문제에 대한 관련 정보를 기록합니다.
+
이러한 목록에 참여하려면 {mailing-lists}로 이동하여 구독할 목록을 클릭하고 안내를 따르세요. 전체 소스 트리의 변경 사항을 추적하려면 {dev-commits-src-all}을 구독하세요.
. 새로운 FreeBSD-STABLE 시스템을 설치하려면, crossref:mirrors[mirrors,FreeBSD mirror sites]에서 가장 최신 FreeBSD-STABLE 릴리스를 설치하거나 FreeBSD-STABLE에서 빌드한 월간 스냅샷을 사용합니다. 스냅샷에 대한 자세한 내용은 link:https://www.FreeBSD.org/snapshots/[www.freebsd.org/snapshots]를 참조하세요.
+
기존 FreeBSD 시스템을 FreeBSD-STABLE로 컴파일하거나 업그레이드하려면, `git` 을 사용하여 원하는 브랜치에 대한 소스를 체크아웃합니다. `stable/13` 과 같은 브랜치 이름은 link:https://www.FreeBSD.org/releng/[www.freebsd.org/releng]에 나열되어 있습니다.
. FreeBSD-STABLE로 컴파일하거나 업그레이드하기 전에 [.filename]#/usr/src/Makefile# 을 주의 깊게 읽고 <<makeworld>> 에 있는 지침을 따르세요. 다음 릴리즈로 가는 과정에서 때때로 필요한 다른 부트스트랩 절차에 대한 최신 정보를 얻으려면 {freebsd-stable} 및 [.filename]#/usr/src/UPDATING# 을 읽으세요.

[[translate-n-number]]
=== N-넘버
버그를 추적할 때는 문제가 있는 시스템을 만드는 데 사용된 소스 코드의 버전을 아는 것이 중요합니다. FreeBSD는 커널에 컴파일된 버전 정보를 제공합니다. 예를 들어, man:uname[1]은 이 정보를 검색합니다:
[source, shell]
....
% uname -v
FreeBSD 14.0-CURRENT #112 main-n247514-031260d64c18: Tue Jun 22 20:43:19 MDT 2021     fred@machine:/usr/home/fred/obj/usr/home/fred/git/head/amd64.amd64/sys/FRED
....
마지막 필드에는 커널 이름, 커널을 만든 사람, 커널이 컴파일된 위치에 관한 정보가 표시됩니다. 네 번째 필드를 살펴보면 여러 부분으로 구성되어 있습니다:
[source, shell]
....
main-n247514-031260d64c18

main		<.>
n247514		<.>
031260d64c18	<.>
		<.>
....
<.> Git 브랜치 이름. 참고: n-넘버 비교는 프로젝트에서 게시한 브랜치( `main`, `stable/XX` 및 `releng/XX` )에서만 유효합니다. 로컬 브랜치는 부모 브랜치의 커밋과 겹치는 n-넘버를 갖게 됩니다.
<.> n-넘버는 줄에 포함된 Git 해시부터 시작하여 Git 저장소의 시작점으로 거슬러 올라가는 커밋의 선형 카운트입니다.
<.> 체크아웃된 트리의 git 해시
<.> 커밋되지 않은 변경 사항이 있는 트리에서 커널이 빌드된 경우 `-dirty` 접미사가 있는 경우가 있습니다. 이 예제에서는 FRED 커널이 깨끗한 체크아웃에서 빌드되었기 때문에 이 접미사가 없습니다.

`git rev-list` 명령은 Git 해시에 해당하는 n-넘버를 찾는 데 사용됩니다. 예를 들어:
[source, shell]
....
% git rev-list --first-parent --count 031260d64c18 <.>
247514 <.>
....
<.> 번역할 git 해시(위 예제의 해시는 재사용됨)
<.> n-넘버.

일반적으로 이 숫자는 그다지 중요하지 않습니다. 하지만 버그 수정이 커밋될 때 이 숫자를 사용하면 현재 실행 중인 시스템에 버그 수정이 있는지 쉽게 확인할 수 있습니다. 개발자는 종종 커밋의 해시를 참조하거나 해당 해시가 있는 URL을 제공하지만, 해시는 변경 사항을 쉽게 식별할 수 있는 식별자이지만 n-넘버는 그렇지 않기 때문에 n-넘버를 사용하지 않습니다. 보안 권고 및 에라타 알림에도 n-넘버가 표시되며, 이를 시스템과 직접 비교할 수 있습니다. 얕은 git 클론을 사용해야 하는 경우, `git rev-list` 명령은 저장소의 모든 리비전 중 얕은 클론이 생략한 리비전을 계산하므로 n-넘버를 안정적으로 비교할 수 없습니다.

[[makeworld]]
== 소스에서 FreeBSD 업데이트하기

소스에서 컴파일하여 FreeBSD를 업데이트하면 바이너리 업데이트에 비해 몇 가지 이점이 있습니다. 특정 하드웨어를 활용하기 위한 옵션을 사용하여 코드를 빌드할 수 있습니다. 기본 시스템의 일부를 기본 설정이 아닌 설정으로 빌드하거나 필요하지 않거나 원하지 않는 부분은 완전히 생략할 수 있습니다. 빌드 프로세스는 바이너리 업데이트를 설치하는 것보다 시스템을 업데이트하는 데 시간이 오래 걸리지만, 완벽한 커스터마이징을 통해 맞춤형 버전의 FreeBSD를 생성할 수 있습니다.

[[updating-src-quick-start]]
=== 빠른 시작

이것은 소스에서 빌드하여 FreeBSD를 업데이트하는 데 사용되는 일반적인 단계에 대한 간략한 참조입니다. 이후 섹션에서는 프로세스에 대해 더 자세히 설명합니다.

[WARNING]
====
man:mergemaster[8]에서 man:etcupdate[8]로 전환할 때, 처음 실행하면 변경 사항을 잘못 병합하여 가짜 충돌을 생성할 수 있습니다. 이를 방지하려면 소스를 업데이트하고 새 월드를 빌드하기 *전에* 다음 단계를 수행하세요:

[source, shell]
....
# etcupdate extract <.>
# etcupdate diff <.>
....

<.> 저장된 [.filename]#/etc# 파일의 데이터베이스를 부트스트랩합니다(자세한 내용은 man:etcupdate[8]를 참조하세요).

<.> 부트스트랩 후 차이점을 확인하세요. 더 이상 필요하지 않은 로컬 변경 사항을 다듬어 향후 업데이트에서 충돌 가능성을 줄이세요.
====

[.procedure]
====
* 업데이트 및 빌드
+
[source, shell]
....
# git pull /usr/src  <.>
check /usr/src/UPDATING  <.>
# cd /usr/src          <.>
# make -j4 buildworld  <.>
# make -j4 kernel      <.>
# shutdown -r now      <.>
# etcupdate -p         <.>
# cd /usr/src          <.>
# make installworld    <.>
# etcupdate -B         <.>
# shutdown -r now      <.>
....

<.> 최신 버전의 소스를 가져옵니다. 소스 가져오기 및 업데이트에 대한 자세한 내용은 <<updating-src-obtaining-src>> 를 참조하세요.

<.> 소스에서 빌드하기 전후에 필요한 수동 단계가 있는지 [.filename]#/usr/src/UPDATING# 을 확인하세요.

<.> 소스 디렉터리로 이동합니다.

<.> 커널을 제외한 모든 월드를 컴파일합니다.

<.> 커널을 컴파일하고 설치합니다. 이것은 `make buildkernel installkernel` 과 동일합니다.

<.> 시스템을 새 커널로 재부팅합니다.

<.> installworld를 하기 전에 [.filename]#/etc/# 에 있는 구성 파일을 업데이트하고 병합합니다.

<.> 소스 디렉터리로 이동합니다.

<.> 월드를 설치합니다.

<.> [.filename]#/etc/# 에 있는 구성 파일을 업데이트하고 병합합니다.

<.> 새로 빌드된 월드와 커널을 사용하려면 시스템을 재시작하세요.
====

[[updating-src-preparing]]
=== 소스 업데이트 준비하기

[.filename]#/usr/src/UPDATING# 를 읽어보세요. 업데이트 전후에 수행해야 하는 모든 수동 단계가 이 파일에 설명되어 있습니다.

[[updating-src-obtaining-src]]
=== 소스 업데이트하기

FreeBSD 소스 코드는 [.filename]#/usr/src/# 에 있습니다. 이 소스를 업데이트하는 가장 좋은 방법은 Git 버전 관리 시스템을 이용하는 것입니다. 소스 코드가 버전 관리 중인지 확인하세요:

[source, shell]
....
# cd /usr/src
# git remote --v
origin  https://git.freebsd.org/src.git (fetch)
origin  https://git.freebsd.org/src.git (push)
....

이는 [.filename]#/usr/src/# 이 버전 관리 중이며 man:git[1]으로 업데이트할 수 있음을 나타냅니다:

[[synching]]
[source, shell]
....
# git pull /usr/src
....

디렉터리를 최근에 업데이트하지 않은 경우 업데이트 프로세스에 시간이 다소 걸릴 수 있습니다. 업데이트가 완료되면 소스 코드가 최신 상태가 되며 다음 섹션에서 설명하는 빌드 프로세스를 시작할 수 있습니다.

[NOTE]
====
*Obtaining the Source:* +

출력에 `fatal: not a git repository` 라고 표시되면 파일이 누락되었거나 다른 방법으로 설치되었다는 뜻입니다. 소스를 새로 체크 아웃해야 합니다.

[[updating-src-obtaining-src-repopath]]
.FreeBSD 버전과 저장소 브랜치
[cols="10%,10%,80%", options="header"]
|===
| uname -r Output
| Repository Path
| Description

|`_X.Y_-RELEASE`
|`releng/_X.Y_`
|The Release version plus only critical security and bug fix patches. This branch is recommended for most users.

|`_X.Y_-STABLE`
|`stable/_X_`
|

The Release version plus all additional development on that branch. _STABLE_ refers to the Applications Binary Interface (ABI) not changing, so software compiled for earlier versions still runs. For example, software compiled to run on FreeBSD 10.1 will still run on FreeBSD 10-STABLE compiled later.

STABLE branches occasionally have bugs or incompatibilities which might affect users, although these are typically fixed quickly.

|`_X_-CURRENT`
|`main`
|The latest unreleased development version of FreeBSD. The CURRENT branch can have major bugs or incompatibilities and is recommended only for advanced users.
|===

man:uname[1]로 사용 중인 FreeBSD 버전을 확인합니다:

[source, shell]
....
# uname -r
13.2-RELEASE
....

<<updating-src-obtaining-src-repopath>> 에 따르면 `13.2-RELEASE` 를 업데이트하는 데 사용된 소스의 저장소 경로는 `releng/13.2` 입니다. 이 경로는 소스를 체크 아웃할 때 사용됩니다:

[source, shell]
....
# mv /usr/src /usr/src.bak <.>
# git clone --branch releng/13.2 https://git.FreeBSD.org/src.git /usr/src <.>
....

<.> 이전 디렉터리를 다른 곳으로 옮깁니다. 이 디렉터리에 로컬 수정 사항이 없는 경우 삭제할 수 있습니다.

<.> <<updating-src-obtaining-src-repopath>> 에서 경로가 저장소 URL에 추가됩니다. 세 번째 매개변수는 로컬 시스템에서 소스 코드의 대상 디렉터리입니다.
====

[[updating-src-building]]
=== 소스에서 빌드하기

_world_ , 즉 커널을 제외한 모든 운영 체제가 컴파일됩니다. 이 작업은 커널을 빌드하기 위한 최신 도구를 제공하기 위해 먼저 수행됩니다. 그런 다음 커널 자체가 빌드됩니다:

[source, shell]
....
# cd /usr/src
# make buildworld
# make buildkernel
....

컴파일된 코드는 [.filename]#/usr/obj# 에 저장됩니다.

이것이 기본 단계입니다. 빌드를 제어하기 위한 추가 옵션은 아래에 설명되어 있습니다.

[[updating-src-building-clean-build]]
==== 클린 빌드 수행하기

일부 버전의 FreeBSD 빌드 시스템은 이전에 컴파일한 코드를 임시 오브젝트 디렉터리인 [.filename]#/usr/obj# 에 남겨둡니다. 이렇게 하면 변경되지 않은 코드를 다시 컴파일하지 않아도 되므로 나중에 빌드 속도를 높일 수 있습니다. 모든 것을 강제로 새로 빌드하려면 빌드를 시작하기 전에 `cleanworld` 를 사용하세요:

[source, shell]
....
# make cleanworld
....

[[updating-src-building-jobs]]
==== 작업의 수 설정하기

멀티코어 프로세서에서 빌드 작업 수를 늘리면 빌드 속도가 향상될 수 있습니다. `sysctl hw.ncpu` 로 코어 수를 결정합니다. 프로세서는 FreeBSD 버전에 따라 사용되는 빌드 시스템과 마찬가지로 다양하므로, 다른 작업 수가 빌드 속도에 어떤 영향을 미치는지 알 수 있는 유일한 확실한 방법은 테스트입니다. 시작점으로 코어 수의 절반에서 두 배 사이의 값을 고려하십시오. 작업의 수는 `-j` 로 지정합니다.

[[updating-src-building-jobs-example]]
.빌드 작업 수 늘리기
[example]
====
네 개의 작업으로 월드와 커널을 빌드하기:

[source, shell]
....
# make -j4 buildworld buildkernel
....

====

[[updating-src-building-only-kernel]]
==== 커널만 빌드하기

소스 코드가 변경된 경우 반드시 `buildworld` 를 먼저 완료해야 합니다. 그 후 커널을 빌드하는 `buildkernel` 은 언제든지 실행할 수 있습니다. 커널만 빌드하려면:

[source, shell]
....
# cd /usr/src
# make buildkernel
....

[[updating-src-building-custom-kernel]]
==== 커스텀 커널 빌드하기

표준 FreeBSD 커널은 [.filename]#GENERIC# 이라는 _커널 구성 파일_ 을 기반으로 합니다. [.filename]#GENERIC# 커널에는 가장 일반적으로 필요한 장치 드라이버와 옵션이 포함되어 있습니다. 때로는 특정 요구에 맞게 장치 드라이버나 옵션을 추가하거나 제거하여 사용자 지정 커널을 빌드하는 것이 유용하거나 필요할 수 있습니다.

예를 들어 RAM이 극도로 제한된 소형 임베디드 컴퓨터를 개발하는 사람은 불필요한 장치 드라이버나 옵션을 제거하여 커널을 조금 더 작게 만들 수 있습니다.

커널 설정 파일은 [.filename]#/usr/src/sys/arch/conf/# 에 위치하며, 여기서 _arch_ 는 `uname -m` 의 출력값입니다. 대부분의 컴퓨터에서 이는 `amd64` 이며, 구성 파일 디렉터리는 [.filename]#/usr/src/sys/amd64/conf/# 입니다.

[TIP]
====
[.filename]#/usr/src# 는 삭제하거나 다시 생성할 수 있으므로 커스텀 커널 구성 파일은 [.filename]#/root# 와 같은 별도의 디렉터리에 보관하는 것이 바람직합니다. 커널 구성 파일을 [.filename]#conf# 디렉터리에 링크합니다. 해당 디렉터리를 삭제하거나 덮어쓰면 커널 구성 파일을 새 디렉터리에 다시 링크할 수 있습니다.
====

사용자 지정 구성 파일은 [.filename]#GENERIC# 구성 파일을 복사하여 만들 수 있습니다. 이 예제에서 새 사용자 지정 커널은 스토리지 서버용이므로 [.filename]#STORAGESERVER# 로 명명됩니다:

[source, shell]
....
# cp /usr/src/sys/amd64/conf/GENERIC /root/STORAGESERVER
# cd /usr/src/sys/amd64/conf
# ln -s /root/STORAGESERVER .
....

그런 다음 [.filename]#/root/STORAGESERVER# 를 편집하여 man:config[5]에 표시된 대로 장치 또는 옵션을 추가하거나 제거합니다.

커스텀 커널은 명령줄에서 커널 구성 파일에 `KERNCONF` 를 설정하여 빌드합니다:

[source, shell]
....
# make buildkernel KERNCONF=STORAGESERVER
....

[[updating-src-installing]]
=== 컴파일된 코드 설치하기

`buildworld` 및 `buildkernel` 단계가 완료되면 새 커널과 월드가 설치됩니다:

[source, shell]
....
# cd /usr/src
# make installkernel
# shutdown -r now
# cd /usr/src
# make installworld
# shutdown -r now
....

커스텀 커널을 빌드한 경우 새 커스텀 커널을 사용하도록 `KERNCONF` 도 설정해야 합니다:

[source, shell]
....
# cd /usr/src
# make installkernel KERNCONF=STORAGESERVER
# shutdown -r now
# cd /usr/src
# make installworld
# shutdown -r now
....

[[updating-src-completing]]
=== 업데이트 완료하기

몇 가지 마지막 작업으로 업데이트가 완료됩니다. 수정된 모든 구성 파일을 새 버전과 병합하고 오래된 라이브러리를 찾아 제거한 다음 시스템을 다시 시작합니다.

[[updating-src-completing-merge-etcupdate]]
==== man:etcupdate[8]로 구성 파일 병합하기

man:etcupdate[8]는 [.filename]#/etc/# 에 있는 파일과 같이 installworld의 일부로 업데이트되지 않는 파일에 대한 업데이트를 관리하는 도구입니다. 이 도구는 로컬 버전에 대해 파일의 변경 사항을 세 방향으로 병합하여 업데이트를 관리합니다. 또한 man:mergemaster[8]의 대화형 프롬프트와 달리 사용자 개입을 최소화하도록 설계되었습니다.

[NOTE]
====
일반적으로 man:etcupdate[8]는 작업에 특정 인수가 필요하지 않습니다. 그러나 man:etcupdate[8]을 처음 사용할 때 수행될 작업을 확인하기 위한 편리한 중간 명령이 있습니다:

[source, shell]
....
# etcupdate diff
....

이 명령을 사용하면 구성 변경 사항을 감사할 수 있습니다.
====

man:etcupdate[8]가 파일을 자동으로 병합할 수 없는 경우, 수동으로 상호작용하여 병합 충돌을 해결할 수 있습니다:

[source, shell]
....
# etcupdate resolve
....

[WARNING]
====
man:mergemaster[8]에서 man:etcupdate[8]로 전환할 때, 처음 실행하면 변경 사항을 잘못 병합하여 가짜 충돌을 생성할 수 있습니다. 이를 방지하려면 소스를 업데이트하고 새 월드를 빌드하기 *전에* 다음 단계를 수행하세요:

[source, shell]
....
# etcupdate extract <.>
# etcupdate diff <.>
....

<.> 저장된 [.filename]#/etc# 파일의 데이터베이스를 부트스트랩합니다(자세한 내용은 man:etcupdate[8]를 참조하세요).

<.> 부트스트랩 후 차이점을 확인하세요. 더 이상 필요하지 않은 로컬 변경 사항을 다듬어 향후 업데이트에서 충돌 가능성을 줄이세요.
====

[[updating-src-completing-merge-mergemaster]]
==== man:mergemaster[8]로 구성 파일 병합하기

man:mergemaster[8]는 시스템 구성 파일에 대한 변경 사항을 해당 파일의 새 버전과 병합하는 방법을 제공합니다. man:mergemaster[8]는 man:etcupdate[8]의 대안으로, `-Ui` 를 사용하여 사용자가 수정하지 않은 파일을 자동으로 업데이트하고 아직 존재하지 않는 새 파일을 설치합니다:

[source, shell]
....
# mergemaster -Ui
....

파일을 반드시 수동으로 병합해야 하는 경우 대화형 디스플레이를 통해 사용자가 파일의 어느 부분을 유지할지 선택할 수 있습니다. 자세한 내용은 man:mergemaster[8]를 참조하세요.

[[updating-src-completing-check-old]]
==== 오래된 파일 및 라이브러리 확인하기

업데이트 후에도 일부 더 이상 사용되지 않는 파일이나 디렉토리가 남아있을 수 있습니다. 다음으로 이러한 파일을 찾을 수 있습니다:

[source, shell]
....
# make check-old
....

그리고 삭제할 수 있습니다:

[source, shell]
....
# make delete-old
....

일부 더 이상 사용되지 않는 라이브러리도 남아있을 수 있습니다. 이러한 라이브러리는 다음을 통해 감지할 수 있습니다:

[source, shell]
....
# make check-old-libs
....

그리고 다음을 통해 삭제할 수 있습니다

[source, shell]
....
# make delete-old-libs
....

이전 라이브러리를 계속 사용하던 프로그램은 라이브러리가 삭제되면 작동이 중지됩니다. 이러한 프로그램은 이전 라이브러리를 삭제한 후 다시 빌드하거나 교체해야 합니다.

[TIP]
====
모든 오래된 파일 또는 디렉터리를 삭제해도 안전하다고 확인된 경우, 명령에서 `BATCH_DELETE_OLD_FILES` 를 설정하면 각 파일을 삭제하기 위해 kbd:[y] 및 kbd:[Enter]를 누르는 것을 피할 수 있습니다. 예를 들어:

[source, shell]
....
# make BATCH_DELETE_OLD_FILES=yes delete-old-libs
....

====

[[updating-src-completing-restart]]
==== 업데이트 후 재시작하기

업데이트 후 마지막 단계는 컴퓨터를 다시 시작하여 모든 변경 사항을 적용하는 것입니다:

[source, shell]
....
# shutdown -r now
....

[[small-lan]]
== 여러 머신을 추적하기

여러 대의 컴퓨터가 동일한 소스 트리를 추적해야 하는 경우, 각각의 시스템이 소스를 다운로드하고 모든 것을 다시 빌드하는 것은 디스크 공간, 네트워크 대역폭, CPU 사이클을 낭비하는 일입니다. 해결책은 한 대의 컴퓨터가 대부분의 작업을 수행하고 나머지 컴퓨터는 NFS를 통해 해당 작업을 마운트하는 것입니다. 이 섹션에서는 그 방법을 간략하게 설명합니다. NFS 사용에 대한 자세한 내용은 crossref:network-servers[network-nfs,"Network File System (NFS)"]을 참조하세요.

먼저, 동일한 바이너리 세트를 실행할 머신 세트를 _빌드 세트_ 라고 합니다. 각 머신은 커스텀 커널을 가질 수 있지만 동일한 사용자 공간 바이너리를 실행합니다. 이 세트에서 월드와 커널이 빌드되는 _빌드 머신_ 이 될 머신을 선택합니다. 이상적으로는 `make buildworld` 와 `make buildkernel` 을 실행할 수 있는 충분한 여유 CPU가 있는 빠른 머신이 이상적입니다.

소프트웨어 업데이트를 프로덕션에 적용하기 전에 테스트할 _테스트 머신_ 이 될 머신을 선택합니다. 이 머신은 장시간 다운될 수 있는 머신이어야 합니다. 빌드 머신일 수도 있지만 _반드시_ 그럴 필요는 없습니다.

이 빌드 세트의 모든 머신은 NFS를 통해 빌드 머신에서 [.filename]#/usr/obj# 및 [.filename]#/usr/src# 를 마운트해야 합니다. 여러 빌드 세트의 경우 [.filename]#/usr/src# 는 한 빌드 머신에, 나머지 머신에는 NFS를 마운트해야 합니다.

빌드 세트에 있는 모든 머신의 [.filename]#/etc/make.conf# 및 [.filename]#/etc/src.conf# 가 빌드 머신과 일치하는지 확인합니다. 즉, 빌드 머신은 빌드 세트의 모든 머신이 설치할 기본 시스템의 모든 부분을 빌드해야 합니다. 또한 각 빌드 머신의 커널 이름은 [.filename]#/etc/make.conf# 에 `KERNCONF` 로 설정되어 있어야 하며, 빌드 머신은 자신의 커널을 먼저 나열하여 `KERNCONF` 에 모든 커널을 나열해야 합니다. 빌드 머신은 각 머신에 대한 커널 구성 파일을 [.filename]#/usr/src/sys/arch/conf# 에 가지고 있어야 합니다.

빌드 머신에서 <<makeworld>> 에 설명된 대로 커널과 월드를 빌드하되, 빌드 머신에 아무것도 설치하지 마세요. 대신 빌드된 커널을 테스트 머신에 설치합니다. 테스트 머신에서 NFS를 통해 [.filename]#/usr/src# 및 [.filename]#/usr/obj# 를 마운트합니다. 그런 다음 `shutdown now` 를 실행하여 단일 사용자 모드로 전환하여 새 커널과 월드를 설치하고 평소와 같이 `mergemaster` 를 실행합니다. 완료되면 재부팅하여 정상적인 다중 사용자 작업으로 돌아갑니다.

테스트 머신의 모든 항목이 제대로 작동하는지 확인한 후 동일한 절차를 사용하여 빌드 세트의 다른 머신에 새 소프트웨어를 설치합니다.

포트 트리에도 동일한 방법론을 사용할 수 있습니다. 첫 번째 단계는 NFS를 통해 빌드 세트의 모든 머신에 [.filename]#/usr/ports# 를 공유하는 것입니다. dist파일을 공유하도록 [.filename]#/etc/make.conf# 를 구성하려면 `DISTDIR` 을 NFS 마운트에 의해 매핑된 사용자 `root` 가 쓰기 가능한 공통 공유 디렉터리로 설정합니다. 포트를 로컬로 빌드할 경우 각 머신은 `WRKDIRPREFIX` 를 로컬 빌드 디렉터리로 설정해야 합니다. 또는 빌드 시스템이 빌드 세트의 머신에 패키지를 빌드하고 배포하는 경우 빌드 시스템의 `PACKAGES` 를 `DISTDIR` 과 유사한 디렉터리로 설정합니다.
