---
description: '이 책의 첫 번째 섹션은 FreeBSD를 처음 접하는 사용자를 위해 FreeBSD 설치 과정을 안내하고 UNIX의 기반이 되는 개념과 규칙을 차근차근 소개합니다'
next: books/handbook/parti
path: /books/handbook/
prev: books/handbook
showBookMenu: 'true'
tags: ["preface", "audience", "organization", "conventions", "acknowledgments"]
title: 머리말
weight: 1
---

[preface]
[[book-preface]]
= 머리말
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/preface/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[preface-audience]]
== 대상 그룹

이 책의 첫 번째 섹션에서는 FreeBSD 설치 과정을 안내하고 UNIX(R)의 기반이 되는 개념과 규칙을 부드럽게 소개합니다. 이 섹션을 따라가려면 새로운 개념이 소개될 때 이를 받아들일 수 있는 능력과 탐구 욕구만 있으면 됩니다.

여기까지 읽으셨다면, 핸드북의 두 번째, 훨씬 더 큰 섹션에서는 FreeBSD 시스템 관리자가 관심을 가질 만한 모든 종류의 주제에 대한 포괄적인 참고자료를 제공합니다. 이 장들 중 일부는 미리 읽어볼 것을 권장할 수 있으며, 각 장의 시작 부분에 요약이 나와 있습니다.

추가 정보 출처 목록은 crossref:bibliography[bibliography,Bibliography]을 참조하세요.

[[preface-changes-from4]]
== 제 4판

현재 버전의 핸드북은 모든 핸드북 콘텐츠를 검토하고 업데이트해온 실무 그룹의 누적된 노력이 반영된 결과물입니다. 다음은 핸드북 4판 이후 업데이트된 주요 내용입니다.

* 핸드북은 link:https://docbook.org/[Docbook]에서 link:https://gohugo.io/[Hugo] 및 link:https://asciidoctor.org/[AsciiDoctor]로 변환되었습니다
* link:https://docs.FreeBSD.org[FreeBSD Documentation Portal]이 생성되었습니다.
* crossref:wayland[wayland,Wayland]에 FreeBSD에서 Wayland 설치 및 구성에 대한 정보가 추가되었습니다.
* crossref:bibliography[bibliography,Bibliography]이 광범위하게 업데이트되었습니다.


[[preface-changes-from3]]
== 제 3판

현재 온라인 버전의 핸드북은 지난 10년간 수백 명의 기고가들이 쌓아온 노력의 결과물입니다. 다음은 2004년에 두 권으로 구성된 3판이 출간된 이후 몇 가지 중요한 변화입니다:

* crossref:wine[wine,WINE]에 FreeBSD에서 Windows(R) 애플리케이션을 실행하는 방법에 대한 정보가 추가되었습니다.
* crossref:dtrace[dtrace,DTrace]에 강력한 DTrace 성능 분석 도구에 대한 정보가 추가되었습니다.
* crossref:filesystems[filesystems,Other File Systems]에 Sun(TM)의 ZFS와 같은 FreeBSD의 비 기본 파일 시스템에 대한 정보가 추가되었습니다.
* crossref:audit[audit,Security Event Auditing]가 추가되어 FreeBSD의 새로운 감사 기능을 다루고 그 사용법을 설명합니다.
* 가상화 소프트웨어에 FreeBSD를 설치하는 방법에 대한 정보가 crossref:virtualization[virtualization,Virtualization]에 추가되었습니다.
* 새로운 설치 유틸리티인 bsdinstall을 사용하여 FreeBSD를 설치하는 방법을 위해 crossref:bsdinstall[bsdinstall,Installing FreeBSD]가 추가되었습니다.

[[preface-changes-from2]]
== 제 2 판 (2004)

세 번째 판은 FreeBSD 문서화 프로젝트의 헌신적인 멤버들이 2년이 넘는 기간 동안 작업한 결과물입니다. 인쇄판의 규모가 커져 두 권으로 나눠서 출판해야 할 정도였습니다. 이번 새 판의 주요 변경사항은 다음과 같습니다:

* crossref:config[config-tuning,Configuration and Tuning]에 ACPI 전원 및 리소스 관리, `cron` 시스템 유틸리티, 더 많은 커널 튜닝 옵션에 대한 새로운 정보가 추가되었습니다.
* crossref:security[security,Security]에 가상 사설망(VPN), 파일 시스템 액세스 제어 목록(ACL) 및 보안 권고에 대한 새로운 정보가 추가되었습니다.
* crossref:mac[mac,Mandatory Access Control]는 이번 버전에서 새로운 장으로 추가되었습니다. 이 장에서는 MAC이 무엇이며, 이 메커니즘을 사용하여 FreeBSD 시스템을 보호하는 방법을 설명합니다.
* crossref:disks[disks,Storage]가 USB 저장 장치, 파일 시스템 스냅샷, 파일 시스템 할당량, 파일 및 네트워크 백업 파일 시스템, 암호화된 디스크 파티션에 대한 새로운 정보로 확장되었습니다.
* crossref:ppp-and-slip[ppp-and-slip,PPP]에 문제 해결 섹션이 추가되었습니다.
* crossref:mail[mail,Electronic Mail]에 대체 전송 에이전트 사용, SMTP 인증, UUCP, fetchmail, procmail 및 기타 고급 주제에 대한 새로운 정보가 추가되어 확장되었습니다.
* crossref:network-servers[network-servers,Network Servers]가 이번 버전에 새로 추가되었습니다. 이 장에는 아파치 HTTP 서버, ftpd 설정 및 Samba를 사용한 Microsoft(R) Windows(R) 클라이언트용 서버 설정에 대한 정보가 포함되어 있습니다. crossref:advanced-networking[advanced-networking,Advanced Networking]의 일부 섹션은 시인성을 개선하기 위해 여기로 옮겼습니다.
* crossref:advanced-networking[advanced-networking,Advanced Networking]은 FreeBSD에서 블루투스(R) 장치 사용, 무선 네트워크 설정, 비동기 전송 모드(ATM) 네트워킹에 대한 새로운 정보로 확장되었습니다.
* 책 전체에 사용된 기술 용어의 정의를 한 곳에서 확인할 수 있도록 용어집을 추가했습니다.
* 책 전체에 걸쳐 표와 그림이 미적으로 많이 개선되었습니다.

[[preface-changes]]
== 초판 (2001)

두 번째 버전은 FreeBSD 문서 프로젝트의 헌신적인 멤버들이 2년 넘게 작업한 결과의 정점입니다. 이번 에디션의 주요 변경 사항은 다음과 같습니다:

* 전체 색인이 추가되었습니다.
* 모든 ASCII 숫자가 그래픽 다이어그램으로 대체되었습니다.
* 각 장에 표준 요약이 추가되어 해당 장에 포함된 정보와 독자가 알아야 할 내용을 간략하게 요약할 수 있습니다.
* 콘텐츠를 논리 흐름에 맞게 세 부분으로 재구성하였습니다: "시작하기", "시스템 관리", "부록"입니다.
* crossref:basics[basics,FreeBSD Basics]가 프로세스, 데몬 및 신호에 대한 추가 정보를 포함하도록 확장되었습니다.
* crossref:ports[ports,Installing Applications: Packages and Ports]가 바이너리 패키지 관리에 대한 추가 정보를 포함하도록 확장되었습니다.
* crossref:x11[x11,The X Window System]은 XFree86(TM) 4.X에서 KDE 및 GNOME과 같은 최신 데스크톱 기술을 사용하는 데 중점을 두고 완전히 재작성되었습니다.
* crossref:boot[boot,The FreeBSD Booting Process]가 확장되었습니다.
* crossref:disks[disks,Storage]는 "디스크"와 "백업"에 대한 두 개의 장으로 분리되어 있던 것을 하나의 장으로 통합하여 작성되었습니다. 하나의 장으로 구성하는 것이 주제를 더 쉽게 이해할 수 있다고 생각했기 때문입니다. RAID(하드웨어 및 소프트웨어 모두)에 대한 섹션도 추가되었습니다.
* crossref:serialcomms[serialcomms,Serial Communications]이 FreeBSD 4.X/5.X용으로 완전히 개편 및 업데이트되었습니다.
* crossref:ppp-and-slip[ppp-and-slip,PPP]이 대폭 업데이트되었습니다.
* crossref:advanced-networking[advanced-networking,Advanced Networking]에 많은 새로운 섹션이 추가되었습니다.
* crossref:mail[mail,Electronic Mail]이 sendmail 구성에 대한 자세한 정보를 포함하도록 확장되었습니다.
* crossref:linuxemu[linuxemu,Linux® Binary Compatibility]에 오라클(R) 및 SAP(R) R/3(R) 설치에 대한 정보를 포함하도록 확장되었습니다.
* 제 2판에서는 다음과 같은 새로운 주제를 다룹니다:

** crossref:config[config-tuning,Configuration and Tuning].
** crossref:multimedia[multimedia,Multimedia].

[[preface-overview]]
== 이 책의 구성

이 책은 논리적으로 구분되는 다섯 개의 섹션으로 나뉩니다. 첫 번째 섹션인 _시작하기_ 에서는 FreeBSD의 설치와 기본 사용법을 다룹니다. 독자들은 이 장들을 순서대로 따라가면서 익숙한 주제를 다루는 장은 건너뛸 수도 있습니다. 두 번째 섹션인 _일반적인 작업_ 에서는 FreeBSD에서 자주 사용되는 몇 가지 기능을 다룹니다. 이 섹션과 그 이후의 모든 섹션은 순서대로 읽을 수 있습니다. 각 장은 해당 장에서 다루는 내용과 독자가 이미 알고 있을 것으로 예상되는 내용을 설명하는 간결한 요약으로 시작됩니다. 이는 일반 독자가 관심 있는 챕터를 찾기 위해 건너뛸 수 있도록 하기 위한 것입니다. 세 번째 섹션인 _시스템 관리_ 에서는 관리 주제를 다룹니다. 네 번째 섹션인 _네트워크 통신_ 에서는 네트워킹 및 서버 주제를 다룹니다. 다섯 번째 섹션에는 참조 정보가 담긴 부록이 포함되어 있습니다.

_crossref:introduction[introduction,Introduction]_::
새로운 사용자에게 FreeBSD를 소개합니다. FreeBSD 프로젝트의 역사, 목표 및 개발 모델을 설명합니다.

_crossref:bsdinstall[bsdinstall,Installing FreeBSD]_::
bsdinstall을 사용하여 FreeBSD 9.x_ 이상의 전체 설치 프로세스를 사용자에게 안내합니다.

_crossref:basics[basics,FreeBSD Basics]_::
FreeBSD 운영 체제의 기본 명령어와 기능을 다룹니다. Linux(R) 또는 다른 버전의 UNIX(R)에 익숙하다면 이 장은 건너뛰어도 됩니다.

_crossref:ports[ports,Installing Applications: Packages and Ports]_::
FreeBSD의 혁신적인 "포트 컬렉션"과 표준 바이너리 패키지로 타사 소프트웨어를 설치하는 방법을 다룹니다.

_crossref:x11[x11,The X Window System]_::
X 윈도우 시스템 전반에 대해 설명하며, 특히 FreeBSD에서 X11을 사용하는 방법을 설명합니다. 또한 KDE 및 GNOME과 같은 일반적인 데스크톱 환경에 대해서도 설명합니다.

_crossref:wayland[wayland,Wayland]_::
Wayland 디스플레이 서버에 대한 전반적인 설명과 특히 FreeBSD에서 Wayland를 사용하는 방법을 설명합니다. Wayfire, Hikari, Sway와 같은 일반적인 컴포지터에 대해서도 설명합니다.

_crossref:desktop[desktop,Desktop Applications]_::
웹 브라우저 및 생산성 제품군과 같은 몇 가지 일반적인 데스크톱 애플리케이션을 나열하고 FreeBSD에 설치하는 방법을 설명합니다.

_crossref:multimedia[multimedia,Multimedia]_::
시스템에 대한 사운드 및 비디오 재생 지원을 설정하는 방법을 보여줍니다. 또한 몇 가지 샘플 오디오 및 비디오 애플리케이션에 대해서도 설명합니다.

_crossref:kernelconfig[kernelconfig,Configuring the FreeBSD Kernel]_::
새 커널을 구성해야 하는 이유를 설명하고 사용자 지정 커널을 구성, 빌드 및 설치하는 방법에 대한 자세한 지침을 제공합니다.

_crossref:printing[printing,Printing]_::
배너 페이지, 프린터 계정 및 초기 설정에 대한 정보를 포함하여 FreeBSD에서 프린터를 관리하는 방법을 설명합니다.

_crossref:linuxemu[linuxemu,Linux® Binary Compatibility]_::
FreeBSD의 Linux(R) 호환성 기능에 대해 설명합니다. 또한 오라클(R) 및 매트릭스(R)와 같이 널리 사용되는 리눅스(R) 애플리케이션에 대한 자세한 설치 지침을 제공합니다.

_crossref:wine[wine,WINE]_::
WINE에 대해 설명하고 자세한 설치 지침을 제공합니다. 또한 WINE의 작동 방식, GUI 도우미 설치 방법, FreeBSD에서 Windows(R) 애플리케이션을 실행하는 방법, 기타 팁과 솔루션에 대해 설명합니다.

_crossref:config[config-tuning,Configuration and Tuning]_::
시스템 관리자가 최적의 성능을 위해 FreeBSD 시스템을 조정하는 데 사용할 수 있는 매개변수에 대해 설명합니다. 또한 FreeBSD에서 사용되는 다양한 구성 파일과 해당 파일을 찾을 수 있는 위치에 대해서도 설명합니다.

_crossref:boot[boot,The FreeBSD Booting Process]_::
FreeBSD 부팅 프로세스를 설명하고 구성 옵션으로 이 프로세스를 제어하는 방법을 설명합니다.

_crossref:security[security,Security]_::
Kerberos, IPsec 및 OpenSSH를 포함하여 FreeBSD 시스템을 안전하게 유지하는 데 사용할 수 있는 다양한 도구에 대해 설명합니다.

_crossref:jails[jails,Jails]_::
Jails 프레임워크와 FreeBSD의 전통적인 chroot 지원에 비해 개선된 jails에 대해 설명합니다.

_crossref:mac[mac,Mandatory Access Control]_::
필수 접근 제어(MAC)가 무엇이며, 이 메커니즘을 사용하여 FreeBSD 시스템을 보호하는 방법을 설명합니다.

_crossref:audit[audit,Security Event Auditing]_::
FreeBSD 이벤트 감사가 무엇인지, 어떻게 설치하고 구성할 수 있는지, 감사 추적을 검사하거나 모니터링할 수 있는 방법을 설명합니다.

_crossref:disks[disks,Storage]_::
FreeBSD로 저장 미디어와 파일 시스템을 관리하는 방법을 설명합니다. 여기에는 물리 디스크, RAID 어레이, 광학 및 테이프 미디어, 메모리 지원 디스크 및 네트워크 파일 시스템이 포함됩니다.

_crossref:geom[geom,GEOM: Modular Disk Transformation Framework]_::
FreeBSD의 GEOM 프레임워크가 무엇이며 지원되는 다양한 RAID 레벨을 구성하는 방법을 설명합니다.

_crossref:zfs[zfs,The OpenZFS storage platform]_::
OpenZFS 스토리지 플랫폼에 대해 설명하고 빠른 시작 가이드와 FreeBSD에서 OpenZFS를 실행하는 고급 주제에 대한 정보를 제공합니다.

_crossref:filesystems[filesystems,Other File Systems]_::
ext2, ext3, ext4와 같은 FreeBSD의 기본 파일 시스템이 아닌 파일 시스템에 대한 지원을 살펴봅니다.

_crossref:virtualization[virtualization,Virtualization]_::
가상화 시스템이 제공하는 기능과 FreeBSD와 함께 사용할 수 있는 방법을 설명합니다.

_crossref:l10n[l10n,Localization - i18n/L10n Usage and Setup]_::
영어 이외의 언어로 FreeBSD를 사용하는 방법을 설명합니다. 시스템 및 애플리케이션 수준 현지화를 모두 다룹니다.

_crossref:cutting-edge[updating-upgrading,Updating and Upgrading FreeBSD]_::
FreeBSD-STABLE, FreeBSD-CURRENT, FreeBSD 릴리즈 간의 차이점을 설명합니다. 개발 시스템을 추적하면 어떤 사용자가 혜택을 받을 수 있는지 설명하고 그 프로세스를 간략하게 설명합니다. 사용자가 시스템을 최신 보안 릴리스로 업데이트하기 위해 취할 수 있는 방법을 설명합니다.

_crossref:dtrace[dtrace,DTrace]_::
FreeBSD에서 Sun(TM)의 DTrace 도구를 구성하고 사용하는 방법을 설명합니다. 동적 추적은 실시간 시스템 분석을 수행하여 성능 문제를 찾는 데 도움이 될 수 있습니다.

_crossref:usb-device-mode[usb-device-mode,USB Device Mode / USB OTG]_::
FreeBSD에서 USB 디바이스 모드와 USB On The Go (USB OTG)의 사용법을 설명합니다.

_crossref:ppp-and-slip[ppp-and-slip,PPP]_::
PPP를 사용하여 FreeBSD에서 원격 시스템에 연결하는 방법을 설명합니다.

_crossref:mail[mail,Electronic Mail]_::
이메일 서버의 다양한 구성요소를 설명하고 가장 많이 사용되는 메일 서버 소프트웨어: sendmail의 간단한 구성 주제를 자세히 살펴봅니다.

_crossref:network-servers[network-servers,Network Servers]_::
네트워크 파일 시스템 서버, 도메인 네임 서버, 네트워크 정보 시스템 서버 또는 시간 동기화 서버로 FreeBSD 머신을 설정하기 위한 자세한 지침과 구성 파일 예제를 제공합니다.

_crossref:firewalls[firewalls,Firewalls]_::
소프트웨어 기반 방화벽의 철학을 설명하고 FreeBSD에서 사용할 수 있는 다양한 방화벽의 구성에 대한 자세한 정보를 제공합니다.

_crossref:advanced-networking[advanced-networking,Advanced Networking]_::
LAN의 다른 컴퓨터와 인터넷 연결 공유, 고급 라우팅 주제, 무선 네트워킹, Bluetooth(R), ATM, IPv6 등 다양한 네트워킹 주제에 대해 설명합니다.

_crossref:mirrors[mirrors,Obtaining FreeBSD]_::
CD롬이나 DVD로 FreeBSD 미디어를 구할 수 있는 다양한 출처와 FreeBSD를 다운로드하고 설치할 수 있는 인터넷의 다양한 사이트를 나열합니다.

_crossref:bibliography[bibliography,Bibliography]_::
이 책은 더 자세한 설명이 필요할 수 있는 다양한 주제를 다루고 있습니다. 참고 문헌에는 본문에 참조된 많은 훌륭한 책이 나열되어 있습니다.

_crossref:eresources[eresources,Resources on the Internet]_::
FreeBSD 사용자가 질문을 게시하고 FreeBSD에 대한 기술적 대화에 참여할 수 있는 다양한 포럼에 대해 설명합니다.

_crossref:pgpkeys[pgpkeys,OpenPGP Keys]_::
여러 FreeBSD 개발자의 PGP 지문을 나열합니다.

[[preface-conv]]
== 이 책에서 사용된 규칙

일관되고 읽기 쉬운 텍스트를 제공하기 위해 책 전체에서 몇 가지 규칙을 따랐습니다.

[[preface-conv-typographic]]
=== 서체 규칙

_이탤릭체_::
파일 이름, URL, 강조 표시된 텍스트, 기술 용어의 첫 번째 사용에는 _이탤릭체_ 글꼴이 사용됩니다.

`모노스페이스`::
오류 메시지, 명령, 환경 변수, 포트 이름, 호스트 이름, 사용자 이름, 그룹 이름, 장치 이름, 변수 및 코드 조각에는 `모노스페이스` 글꼴이 사용됩니다.

굵은 글꼴::
애플리케이션, 명령 및 키에는 *굵은* 글꼴이 사용됩니다.

[[preface-conv-commands]]
=== 사용자 입력

키는 다른 텍스트와 눈에 잘 띄도록 *굵은체*로 표시됩니다. 동시에 입력해야 하는 키 조합은 다음과 같이 키 사이에 `+` 가 표시되어 있습니다:

kbd:[Ctrl+Alt+Del]

즉, 사용자는 kbd:[Ctrl], kbd:[Alt], kbd:[Del] 키를 동시에 입력해야 합니다.

예를 들어 순서대로 입력해야 하는 키는 쉼표로 구분됩니다:

kbd:[Ctrl+X], kbd:[Ctrl+S]

이는 사용자가 kbd:[Ctrl]과 kbd:[X] 키를 동시에 입력한 다음 kbd:[Ctrl]과 kbd:[S] 키를 동시에 입력해야 한다는 의미입니다.

[[preface-conv-examples]]
=== 예시

[.filename]#C:\># 로 시작하는 예는 MS-DOS(R) 명령을 나타냅니다. 달리 명시되지 않는 한, 이러한 명령은 최신 Microsoft(R) Windows(R) 환경의 "명령 프롬프트" 창에서 실행할 수 있습니다.

[source, shell]
....
C:\> tools\fdimage floppies\kern.flp A:
....

"#"으로 시작하는 예는 FreeBSD에서 수퍼유저로 호출해야 하는 명령을 나타냅니다. `root` 로 로그인하여 명령을 입력하거나 일반 계정으로 로그인하고 man:su[1]을 사용하여 수퍼유저 권한을 얻을 수 있습니다.

[source, shell]
....
# dd if=kern.flp of=/dev/fd0
....

"%"로 시작하는 예는 일반 사용자 계정에서 호출해야 하는 명령을 나타냅니다. 달리 명시되지 않는 한, 환경 변수 설정 및 기타 셸 명령에는 C-shell 구문이 사용됩니다.

[source, shell]
....
% top
....

[[preface-acknowledgements]]
== 감사의 말

여러분이 들고 계신 이 책은 전 세계 수백 명의 사람들의 노력의 결과물입니다. 오타 수정을 보내주셨든, 전체 챕터를 제출해 주셨든, 모든 기여는 유용했습니다.

여러 회사들이 저자들에게 풀타임으로 일할 수 있도록 돈을 지불하고, 출판 비용을 지불하는 등 이 문서의 개발을 지원했습니다. 특히, 2000년 3월에 첫 번째 인쇄본(ISBN 1-57176-241-8)이 발행될 때까지 BSDi(이후 http://www.windriver.com[Wind River Systems]에 인수됨)는 FreeBSD 문서화 프로젝트의 회원들에게 이 책의 개선 작업에 전임으로 일할 수 있도록 비용을 지불했습니다. 그 후 Wind River Systems는 인쇄 출력 인프라를 개선하고 본문에 챕터를 추가하기 위해 여러 명의 저자에게 추가 비용을 지불했습니다. 이 작업은 2001년 11월에 두 번째 인쇄판(ISBN 1-57176-303-1)을 발행하면서 절정에 달했습니다. 2003-2004년, http://www.freebsdmall.com[FreeBSD Mall, Inc]는 세 번째 인쇄판을 준비하면서 핸드북을 개선하기 위해 여러 기고자에게 돈을 지불했습니다. 세 번째 인쇄판은 두 권으로 나뉘어졌습니다. 두 권 모두 FreeBSD 핸드북 제3판 1권: 사용자 가이드(ISBN 1-57176-327-9)와 FreeBSD 핸드북 제3판 2권: 관리자 가이드(ISBN 1-57176-328-7)로 출판되었습니다.
