---
description: '이 장에서는 웹 브라우저, 생산성 소프트웨어, 문서 뷰어, 금융 소프트웨어 등 다양한 데스크톱 환경을 설치하는 방법을 설명합니다'
next: books/handbook/multimedia
part: '파트 II. 일반적인 작업'
path: /books/handbook/
prev: books/handbook/partii
showBookMenu: 'true'
tags: ["desktop", "KDE Plasma", "GNOME", "XFCE", "MATE", "Cinnamon", "LXQT", "browsers", "Firefox", "Chromium", "Iridium", "Falkon", "Konqueror", "Epiphany", "qutebrowser", "Dillo", "Links", "w3m", "Development tools", "Visual Studio Code", "Qt Creator", "Kdevelop", "Eclipse IDE", "Vim", "Neovim", "GNU Emacs", "Productivity", "LibreOffice", "Calligra", "AbiWord", "Viewers", "Okular", "Evince", "ePDFView", "Xpdf", "Finance", "KMyMoney", "GnuCash"]
title: '7장. 데스크톱 환경'
weight: 10
---

[[desktop]]
= 데스크톱 환경
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 7
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/desktop/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[desktop-synopsis]]
== 요약

FreeBSD는 성능과 안정성으로 인해 서버로 인기가 높지만, 일상적인 데스크톱으로 사용하기에도 적합합니다. FreeBSD 포트 트리에서 사용할 수 있는 {numports}개 이상의 애플리케이션을 사용하면 다양한 데스크톱 애플리케이션을 실행할 수 있는 맞춤형 데스크톱을 쉽게 구축할 수 있습니다. 이 장에서는 웹 브라우저, 생산성 소프트웨어, 문서 뷰어 및 금융 소프트웨어와 같은 데스크톱 애플리케이션뿐만 아니라 널리 사용되는 데스크톱 환경을 설치하는 방법을 설명합니다.

사전 요구 사항:

* 이 장의 독자들은 이미 FreeBSD에 crossref:x11[x11,X Window System] or crossref:wayland[wayland,Wayland]를 설치하는 방법을 이해하고 있을 것입니다.
* 이 장에서는 독자들에게 공식 패키지를 설치하는 방법을 설명합니다. 포트에서 사용자 정의 패키지를 빌드하려면 crossref:ports[ports-using,using the ports collection] 섹션을 참조하세요.

[[desktop-environments]]
== 데스크톱 환경

이 섹션에서는 FreeBSD 시스템에서 자주 사용되는 데스크톱 환경을 설치하고 구성하는 방법을 설명합니다. 데스크톱 환경은 간단한 창 관리자부터 완전한 데스크톱 애플리케이션 제품군까지 다양합니다.

.지원되는 데스크톱 환경
[options="header", cols="1,1,1"]
|===
| Name | License | Package

| KDE Plasma
| GPL 2.0 or later
| x11/kde5

| GNOME
| GPL 2.0 or later
| x11/gnome

| XFCE
| GPL, LGPL, BSD
| x11-wm/xfce4

| MATE
| GPL 2.0, LGPL 2.0
| x11/mate

| Cinnamon
| GPL 2.0 or later
| x11/cinnamon

| LXQT
| GPL, LGPL
| x11-wm/lxqt

|===

[[kde-environment]]
=== KDE Plasma

KDE 플라즈마는 사용하기 쉬운 데스크톱 환경입니다. 이 데스크톱은 일관된 모양과 느낌, 표준화된 메뉴 및 도구 모음, 키 바인딩, 색상 체계, 국제화, 중앙 집중식 대화 상자 중심의 데스크톱 구성을 갖춘 애플리케이션 제품군을 제공합니다. KDE에 대한 자세한 정보는 https://kde.org/[KDE 홈페이지]에서 확인할 수 있습니다. FreeBSD 관련 정보는 링크:https://freebsd.kde.org/[KDE의 FreeBSD 홈페이지]를 참조하세요.

[[kde-meta-install]]
==== KDE Plasma 메타 패키지 설치

KDE 프레임워크와 함께 KDE 플라즈마 메타 패키지를 설치하려면 플라즈마 데스크톱 및 애플리케이션을 실행합니다:

[source, shell]
....
# pkg install kde5
....

[[kde-minimal-install]]
==== KDE Plasma 최소 설치

KDE 플라즈마 minimal 버전을 설치하려면:

[source, shell]
....
# pkg install plasma5-plasma
....

[TIP]
====
이 설치는 *진짜* 최소한의 설치입니다. 콘솔은 별도로 실행하여 설치해야 합니다:

[source, shell]
....
# pkg install konsole
....
====

[[kde-configuration]]
==== KDE Plasma 구성

KDE Plasma는 메시지 버스와 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 KDE Plasma의 종속성으로 자동 설치됩니다.

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 D-BUS 서비스를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

메시지 크기를 늘리려면:

[source, shell]
....
sysctl net.local.stream.recvspace=65536
sysctl net.local.stream.sendspace=65536
....

[[kde-start]]
==== KDE Plasma 시작

기본 설정 KDE Plasma 디스플레이 관리자는 package:x11/sddm[] 입니다. package:x11/sddm[]을 설치하려면 실행합니다:

[source, shell]
....
# pkg install sddm
....

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 SDDM 서비스를 활성화합니다:

[source, shell]
....
# sysrc sddm_enable="YES"
....

키보드 언어는 다음 명령(예: 스페인어)을 실행하여 SDDM에서 설정할 수 있습니다:

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

두 번째 방법은 man:startx[1]를 수동으로 호출하여 KDE Plasma를 시작하는 것입니다. 이 방법이 작동하려면 ~/.xinitrc에 다음 줄이 필요합니다:

[source, shell]
....
% echo "exec ck-launch-session startplasma-x11" > ~/.xinitrc
....

[[gnome-environment]]
=== GNOME

GNOME은 사용자 친화적인 데스크톱 환경입니다. 여기에는 애플리케이션을 시작하고 상태를 표시하는 패널, 바탕 화면, 도구 및 애플리케이션 세트, 애플리케이션이 서로 쉽게 협력하고 일관성을 유지할 수 있도록 하는 일련의 규칙이 포함되어 있습니다.

[[gnome-meta-install]]
==== GNOME 메타 패키지 설치

GNOME 데스크톱 및 애플리케이션과 함께 GNOME 메타 패키지를 설치하려면:

[source, shell]
....
# pkg install gnome
....

[[gnome-minimal-install]]
==== 최소한의 GNOME 설치

기본 기능만 간소화한 GNOME 데스크톱이 포함된 GNOME-lite 메타 패키지를 설치하려면 다음을 실행합니다:

[source, shell]
....
# pkg install gnome-lite
....

[[gnome-configuration]]
==== GNOME 구성

GNOME을 사용하려면 `/proc` 를 마운트해야 합니다. 시스템 시작 시 이 파일 시스템을 자동으로 마운트하려면 `/etc/fstab` 에 이 줄을 추가합니다:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

GNOME은 메시지 버스와 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 GNOME의 종속성으로 자동 설치됩니다.

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 D-BUS 서비스를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[gnome-start]]
==== GNOME 시작

GNOME 디스플레이 관리자는 GNOME에서 기본 설정된 디스플레이 관리자입니다. GDM은 GNOME 패키지의 일부로 설치됩니다.

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 GDM을 활성화합니다:

[source, shell]
....
# sysrc gdm_enable="YES"
....

GNOME을 시작하는 두 번째 방법은 man:startx[1]을 수동으로 호출하는 것입니다. 이 방법이 작동하려면 `~/.xinitrc` 에 다음 줄이 필요합니다:

[source, shell]
....
% echo "exec gnome-session" > ~/.xinitrc
....

[[xfce-environment]]
=== XFCE

XFCE는 GTK+를 기반으로 하는 데스크톱 환경으로 가볍고 간단하고 효율적이며 사용하기 쉬운 데스크톱을 제공합니다. 메뉴, 애플릿, 애플리케이션 런처가 있는 메인 패널이 있고 파일 관리자와 사운드 관리자를 제공하며 테마 설정이 가능합니다. 빠르고 가볍고 효율적이기 때문에 메모리 제한이 있는 구형 또는 느린 컴퓨터에 이상적입니다.

[[xfce-install]]
==== XFCE 설치

XFCE 메타 패키지를 설치하려면:

[source, shell]
....
# pkg install xfce
....

[[xfce-configuration]]
==== XFCE 구성

XFCE는 `/proc` 을 마운트해야 합니다. 시스템 시작 시 이 파일 시스템을 자동으로 마운트하려면 `/etc/fstab` 에 다음 줄을 추가하세요:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

XFCE는 메시지 버스 및 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 XFCE의 종속성으로 자동 설치됩니다.

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 D-BUS를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[xfce-start]]
==== XFCE 시작

package:x11/lightdm[]은 다양한 디스플레이 기술을 지원하는 디스플레이 관리자로, 매우 가볍고 메모리 사용량이 적으며 성능이 빠르기 때문에 좋은 선택입니다.

설치하려면:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 lightdm을 활성화합니다:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

두 번째 방법은 man:startx[1]을 수동으로 호출하여 XFCE를 시작하는 것입니다. 이 방법이 작동하려면 `~/.xinitrc` 에 다음 줄이 필요합니다:

[source, shell]
....
% echo '. /usr/local/etc/xdg/xfce4/xinitrc' > ~/.xinitrc
....

[[mate-environment]]
=== MATE

MATE 데스크톱 환경은 GNOME 2의 후속 버전입니다.
// What does "traditional metaphors" mean?
전통적인 은유를 사용하여 직관적이고 매력적인 데스크톱 환경을 제공합니다.

[[mate-meta-install]]
==== MATE 메타 패키지 설치

텍스트 편집기, 아카이버 관리자 등 몇 가지 추가 애플리케이션과 함께 MATE 데스크톱이 포함된 MATE 메타 패키지를 설치하려면:

[source, shell]
....
# pkg install mate
....

[[mate-minimal-install]]
==== MATE 최소설치

기본 기능만 간소화한 MATE 라이트 메타 패키지를 설치하려면:

[source, shell]
....
# pkg install mate-base
....

[[mate-configuration]]
==== MATE 구성

MATE를 사용하려면 `/proc` 을 마운트해야 합니다. 시스템 시작 시 이 파일 시스템을 자동으로 마운트하려면 `/etc/fstab` 에 이 줄을 추가하세요:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

MATE는 메시지 버스 및 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 MATE의 종속성으로 자동 설치됩니다. 시스템 부팅 시 시작하려면 `/etc/rc.conf` 에서 D-BUS를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[mate-start]]
==== MATE 시작

package:x11/lightdm[]은 다양한 디스플레이 기술을 지원하는 디스플레이 관리자로, 매우 가볍고 메모리 사용량이 적으며 성능이 빠르기 때문에 좋은 선택입니다.

설치하려면:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 lightdm을 활성화합니다:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

MATE를 시작하는 두 번째 방법은 man:startx[1]을 수동으로 호출하는 것입니다. 이 방법이 작동하려면 `~/.xinitrc` 에 다음 줄이 필요합니다:

[source, shell]
....
% echo "exec ck-launch-session mate-session" > ~/.xinitrc
....

[[cinnamon-environment]]
=== Cinnamon

Cinnamon은 혁신적인 고급 기능과 전통적인 사용자 경험을 제공하는 UNIX(R) 데스크톱입니다. 데스크탑 레이아웃은 Gnome 2와 유사합니다. 기본 기술은 Gnome Shell에서 포크되었습니다. 사용자가 집과 같은 편안함을 느끼고 사용하기 쉽고 편안한 데스크톱 환경을 제공하는 데 중점을 두었습니다.

[[cinnamon-install]]
==== Cinnamon 설치

Cinnamon 패키지를 설치하려면:

[source, shell]
....
# pkg install cinnamon
....

[[cinnamon-configuration]]
==== Cinnamon 구성

Cinnamon은 `/proc` 을 마운트해야 합니다. 시스템 시작 시 이 파일 시스템을 자동으로 마운트하려면 `/etc/fstab` 에 다음 줄을 추가하세요:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

Cinnamon은 메시지 버스와 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 Cinnamon의 종속성으로 자동 설치됩니다. 시스템 부팅 시 시작하려면 `/etc/rc.conf` 에서 D-BUS를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[cinnamon-start]]
==== Cinnamon 시작

package:x11/lightdm[]은 다양한 디스플레이 기술을 지원하는 디스플레이 관리자로, 매우 가볍고 메모리 사용량이 적으며 성능이 빠르기 때문에 좋은 선택입니다.

패키지를 설치하려면:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 lightdm을 활성화합니다:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

두 번째 방법은 man:startx[1]을 수동으로 호출하여 Cinnamon을 시작하는 것입니다. 이 방법이 작동하려면 `~/.xinitrc` 에 다음 줄이 필요합니다:

[source, shell]
....
% echo "exec ck-launch-session cinnamon-session" > ~/.xinitrc
....

[[lxqt-environment]]
=== LXQT

LXQt는 Qt 기술을 기반으로 한 사용하기 쉽고 빠른 고급 데스크톱 환경입니다. 단순성, 속도, 직관적인 인터페이스를 중시하는 사용자를 위해 맞춤 제작되었습니다. 대부분의 데스크톱 환경과 달리 LXQt는 성능이 낮은 컴퓨터에서도 잘 작동합니다.

[[lxqt-install]]
==== LXQT 설치

LXQ 메타 패키지를 설치하려면:

[source, shell]
....
# pkg install lxqt
....

[[lxqt-configuration]]
==== LXQT 구성

LXQT를 마운트하려면 `/proc` 가 필요합니다. 시스템 시작 시 이 파일 시스템을 자동으로 마운트하려면 `/etc/fstab` 에 이 줄을 추가하세요:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

LXQT는 메시지 버스 및 하드웨어 추상화를 위해 man:dbus-daemon[1]을 사용합니다. 이 애플리케이션은 LXQT의 종속성으로 자동 설치됩니다.

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 D-BUS를 활성화합니다:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[lxqt-start]]
==== LXQT 시작

기본 설정 LXQT 디스플레이 관리자는 package:x11/sddm[] 입니다. package:x11/sddm[]을 설치하려면 실행합니다:

[source, shell]
....
# pkg install sddm
....

시스템 부팅 시 시작되도록 `/etc/rc.conf` 에서 SDDM 서비스를 활성화합니다:

[source, shell]
....
# sysrc sddm_enable="YES"
....

키보드 언어는 다음 명령(예: 스페인어)을 실행하여 SDDM에서 설정할 수 있습니다:

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

두 번째 방법은 man:startx[1]을 수동으로 호출하여 LXQT를 시작하는 것입니다. 이 방법이 작동하려면 `~/.xinitrc` 에 다음 줄이 필요합니다:

[source, shell]
....
% echo "exec ck-launch-session startlxqt" > ~/.xinitrc
....

[[desktop-browsers]]
== 브라우저

이 섹션에서는 리소스 소비가 많은 풀 웹 브라우저부터 리소스 사용량이 적은 명령줄 웹 브라우저에 이르기까지 FreeBSD 시스템에 널리 사용되는 몇 가지 웹 브라우저를 설치하고 구성하는 방법을 설명합니다.

.지원되는 브라우저
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Firefox
| MPL 2.0
| package:www/firefox[]
| Heavy

| Chromium
| BSD-3 and others
| package:www/chromium[]
| Heavy

| Iridium browser
| BSD-3 and others
| package:www/iridium[]
| Heavy

| Falkon
| MPL 2.0
| package:www/falkon[]
| Heavy

| Konqueror
| GPL 2.0 or later
| package:x11-fm/konqueror[]
| Medium

| Gnome Web (Epiphany)
| GPL 3.0 or later
| package:www/epiphany[]
| Medium

| qutebrowser
| GPL 3.0 or later
| package:www/qutebrowser[]
| Medium

| Dillo
| GPL 3.0 or later
| package:www/dillo2[]
| Light

| Links
| GPL 2.0 or later
| package:www/links[]
| Light

| w3m
| MIT
| package:www/w3m[]
| Light

|===

[[firefox]]
=== Firefox

Firefox는 표준 준수 HTML 디스플레이 엔진, 탭 브라우징, 팝업 차단, 확장 기능, 향상된 보안 등의 기능을 갖춘 오픈 소스 브라우저입니다. Firefox는 Mozilla 코드베이스를 기반으로 합니다.

최신 릴리스 버전의 Firefox 패키지를 설치하려면:

[source, shell]
....
# pkg install firefox
....

대신 Firefox ESR(확장 지원 릴리스) 버전을 설치하려면:

[source, shell]
....
# pkg install firefox-esr
....

[[chromium]]
=== Chromium

크로미움(Chromium)은 더 안전하고 빠르며 안정적인 웹 브라우징 환경을 구축하는 것을 목표로 하는 오픈소스 브라우저 프로젝트입니다. 크로미움은 탭 브라우징, 팝업 차단, 확장 기능 등을 제공합니다. 크로미움은 구글 크롬 웹 브라우저의 기반이 되는 오픈소스 프로젝트입니다.

Chromium을 설치하려면:

[source, shell]
....
# pkg install chromium
....

[NOTE]
====
Chromium의 실행 파일은 [.filename]#/usr/local/bin/chrome# 이 아니라 [.filename]#/usr/local/bin/chromium# 입니다.
====

[[iridium]]
=== Iridium browser

Iridium은 Chromium 코드 베이스를 수정한 무료 개방형 브라우저로, 몇 가지 주요 영역에서 개인정보 보호가 강화되었습니다. 부분 쿼리, 키워드, 메트릭을 중앙 서비스로 자동 전송하는 것은 금지되어 있으며 동의가 있을 때만 이루어집니다.

Iridium을 설치하려면:

[source, shell]
....
# pkg install iridium
....

[[falkon]]
=== Falkon

Falkon은 새롭고 매우 빠른 QtWebEngine 브라우저입니다. 모든 주요 플랫폼에서 사용할 수 있는 경량 웹 브라우저를 목표로 합니다. Falkon은 웹 브라우저에서 기대할 수 있는 모든 표준 기능을 갖추고 있습니다. 여기에는 북마크, 방문 기록(사이드바에도 있음), 탭이 포함됩니다. 그 외에도 내장된 AdBlock 플러그인으로 광고를 차단하고, Click2Flash로 플래시 콘텐츠를 차단하고, SSL 관리자로 로컬 CA 인증서 데이터베이스를 편집할 수 있습니다.

Falkon을 설치하려면:

[source, shell]
....
# pkg install falkon
....

[[konqueror]]
=== Konqueror

Konqueror는 파일 관리자이자 멀티미디어 뷰어이기도 하므로 웹 브라우저 그 이상입니다. Chromium을 비롯한 많은 최신 브라우저에서 사용하는 렌더링 엔진인 WebKit과 자체 KHTML 엔진을 지원합니다.

Konqueror를 설치하려면:

[source, shell]
....
# pkg install konqueror
....

[[gnome-web-epiphany]]
=== Gnome Web (Epiphany)

Gnome Web(Epiphany)은 다른 브라우저에서 볼 수 있는 많은 기능을 희생하는 대신 최대한 가볍고 빠르게 설계된 웹 브라우저입니다.

Gnome Web(Epiphany)을 설치하려면:

[source, shell]
....
# pkg install epiphany
....

[[qutebrowser]]
=== qutebrowser

Qutebrowser는 최소한의 GUI를 갖춘 키보드 중심의 브라우저입니다. Python과 PyQt5를 기반으로 하며 GPL 라이선스가 부여된 무료 소프트웨어입니다.
// What are these and how does this information help in this context?
이것은 dwb, Vimperator/Pentadactyl과 같은 다른 브라우저/애드온에서 영감을 받았습니다.

qutebrowser를 설치하려면:

[source, shell]
....
# pkg install qutebrowser
....

[[dillo]]
=== Dillo

Dillo는 작고, 안정적이며, 개발자 친화적이고, 사용하기 쉽고, 빠르고, 확장 가능한 멀티플랫폼 대안 브라우저를 목표로 합니다. 이 새롭고 실험적인 Dillo 버전은 GTK1이 아닌 FLTK 툴킷을 기반으로 하며, 상당 부분 재작성되었습니다.

Dillo를 설치하려면:

[source, shell]
....
# pkg install dillo2
....

[[links]]
=== Links

표, 메뉴 등의 표시와 같은 다양한 기능을 갖춘, 텍스트 및 그래픽 모드가 있는 lynx-like WWW 브라우저입니다.

Links를 설치하려면:

[source, shell]
....
# pkg install links
....

[[w3m]]
=== w3m

w3m은 pager/text 기반 웹 브라우저입니다. Lynx와 유사한 애플리케이션이지만 테이블 렌더링 및 프레임 렌더링과 같이 Lynx에는 없는 몇 가지 기능이 있습니다.

w3m을 설치하려면:

[source, shell]
....
# pkg install w3m
....

[[desktop-development]]
== 개발 도구

이 섹션에서는 FreeBSD 시스템에서 몇 가지 인기 있는 개발 도구를 설치하고 구성하는 방법을 설명합니다.

.지원되는 개발 도구
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Visual Studio Code
| MIT
| package:editors/vscode[]
| Heavy

| Qt Creator
| QtGPL
| package:devel/qtcreator[]
| Heavy

| Kdevelop
| GPL 2.0 or later and LGPL 2.0 or later
| package:devel/kdevelop[]
| Heavy

| Eclipse IDE
| EPL
| package:java/eclipse[]
| Heavy

| Vim
| VIM
| package:editors/vim[]
| Light

| Neovim
| Apache 2.0
| package:editors/neovim[]
| Light

| GNU Emacs
| GPL 3.0 or later
| package:editors/emacs[]
| Light

|===

[[vs-code]]
=== Visual Studio Code

Visual Studio Code는 코드 편집기의 단순함과 개발자의 핵심 편집-빌드-디버그 주기에 필요한 기능을 결합한 도구 유형입니다. 포괄적인 편집 및 디버깅 지원, 확장성 모델, 기존 도구와의 가벼운 통합을 제공합니다.

Visual Studio Code를 설치하려면:

[source, shell]
....
# pkg install vscode
....

[[qt-creator]]
=== Qt Creator

Qt Creator는 Qt 개발자의 요구에 맞춘 크로스 플랫폼 IDE(통합 개발 환경)입니다. Qt Creator에 포함된 기능은 다음과 같습니다:

* C++, QML 및 ECMAscript를 지원하는 코드 편집기;
* 빠른 코드 탐색 도구;
* 입력할 때 정적 코드 검사 및 스타일 힌트;
* 상황에 맞는 도움말;
* 시각적 디버거;
* 통합 GUI 레이아웃 및 양식 디자이너.

Qt Creator를 설치하려면:

[source, shell]
....
# pkg install qtcreator
....

[[kdevelop]]
=== kdevelop

C/C++ 및 기타 프로그래밍 언어를 위한 오픈 소스, 완전한 기능, 플러그인 확장 가능 IDE. 1998년부터 개발되어 온 KDevPlatform과 KDE 및 Qt 라이브러리를 기반으로 합니다.

kdevelop를 설치하려면:

[source, shell]
....
# pkg install kdevelop
....

[[eclipse]]
=== Eclipse IDE

Eclipse 플랫폼은 모든 것을 위한 확장 가능한 개방형 IDE입니다. Eclipse 플랫폼은 통합 소프트웨어 개발 도구를 구성하고 실행하기 위한 빌딩 블록과 기반을 제공합니다. 도구 빌더는 이클립스 플랫폼을 통해 다른 사람의 도구와 통합되는 도구를 독립적으로 개발할 수 있습니다.

Eclipse IDE를 설치하려면:

[source, shell]
....
# pkg install eclipse
....

[[vim]]
=== Vim

Vim은 효율적인 텍스트 편집이 가능하도록 고도로 구성 가능한 텍스트 편집기입니다. 대부분의 UNIX 시스템과 함께 배포되는 vi 편집기의 개선된 버전입니다.

Vim은 흔히 "프로그래머를 위한 편집기"라고 불리며, 프로그래밍에 매우 유용하여 많은 사람들이 전체 IDE로 간주합니다. 하지만 프로그래머만을 위한 것은 아닙니다. Vim은 이메일 작성부터 구성 파일 편집까지 모든 종류의 텍스트 편집에 적합합니다.

Vim을 설치하려면:

[source, shell]
....
# pkg install vim
....

[[neovim]]
=== Neovim

Neovim은 package:editors/vim[]의 공격적인 재작성판입니다. 합리적인 기본값, 내장 터미널 에뮬레이터, 비동기 플러그인 아키텍처, 속도와 확장성을 위해 설계된 강력한 API 등 많은 부분이 개선된 코드베이스의 전면적인 개편을 의미합니다. 거의 모든 Vim 플러그인 및 스크립트와의 완벽한 호환성을 유지합니다.

네오빔을 설치하려면:

[source, shell]
....
# pkg install neovim
....

[[gnu-emacs]]
=== GNU Emacs

GNU Emacs는 확장 가능하고 사용자 정의가 가능한 무료/자유 텍스트 편집기입니다. 그 핵심은 텍스트 편집을 지원하는 확장 기능을 갖춘 Lisp 프로그래밍 언어의 방언인 Emacs Lisp용 인터프리터입니다.

GNU Emac을 설치하려면:

[source, shell]
....
# pkg install emacs
....

[[desktop-productivity]]
== 데스크톱 오피스 생산성

생산성과 관련하여 사용자는 종종 오피스 제품군이나 사용하기 쉬운 워드 프로세서를 찾습니다. <<kde-environment, KDE Plasma>> 와 같은 일부 데스크탑 환경에서는 오피스 제품군을 제공하지만, 기본 생산성 패키지는 없습니다. 설치된 데스크탑 환경과 상관없이 FreeBSD에서는 여러 가지 오피스 제품군과 그래픽 워드 프로세서를 사용할 수 있습니다.

이 섹션에서는 다음과 같은 인기 있는 생산성 소프트웨어를 설치하는 방법을 설명하고 해당 애플리케이션이 리소스를 많이 사용하거나, 포트에서 컴파일하는 데 시간이 걸리거나, 주요 종속성이 있는지를 알려줍니다.

.지원되는 데스크톱 오피스 생산성 제품군
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| LibreOffice
| MPL 2.0
| package:editors/libreoffice[]
| Heavy

| Calligra Suite
| LGPL and GPL
| package:editors/calligra[]
| Medium

| AbiWord
| GPL 2.0 or later
| package:editors/abiword[]
| Medium

|===

[[libreoffice]]
=== LibreOffice

LibreOffice는 http://www.documentfoundation.org/[The Document Foundation]에서 개발한 무료 소프트웨어 오피스 제품군입니다. 다른 주요 오피스 제품군과 호환되며 다양한 플랫폼에서 사용할 수 있습니다. 리브레오피스는 아파치 오픈오피스의 리브랜딩된 포크이며 워드 프로세서, 스프레드시트, 프레젠테이션 관리자, 그리기 프로그램, 데이터베이스 관리 프로그램, 수학 공식 작성 및 편집 도구 등 완전한 오피스 생산성 제품군에서 볼 수 있는 애플리케이션이 포함되어 있습니다. 다양한 언어로 제공되며 인터페이스, 맞춤법 검사기, 사전까지 국제화가 확장되었습니다. LibreOffice에 대한 자세한 정보는 http://www.libreoffice.org/[libreoffice.org]에서 확인할 수 있습니다.

LibreOffice를 설치하려면:

[source, shell]
....
# pkg install libreoffice
....

LibreOffice 패키지는 기본적으로 영어로만 제공됩니다. 현지화된 버전의 LibreOffice를 사용하려면 언어 팩을 설치해야 합니다. 예를 들어 스페인어로 현지화된 버전의 경우, package:editors/libreoffice-es[] 명령으로 패키지를 설치해야 합니다:

[source, shell]
....
# pkg install libreoffice-es
....

[[calligra]]
=== Calligra

KDE Plasma 데스크톱 환경에는 KDE Plasma와 별도로 설치할 수 있는 오피스 제품군이 포함되어 있습니다. Calligra에는 다른 오피스 제품군에서 찾을 수 있는 표준 구성 요소가 포함되어 있습니다. Words는 워드 프로세서, Sheets는 스프레드시트 프로그램, Stage는 슬라이드 프레젠테이션, Karbon은 그래픽 문서를 만드는데 사용됩니다.

Calligra를 설치하려면:

[source, shell]
....
# pkg install calligra
....

[[abiword]]
=== AbiWord

AbiWord는 Microsoft(R) Word와 모양과 느낌이 비슷한 무료 워드 프로세싱 프로그램입니다. 빠르고 다양한 기능이 포함되어 있으며 사용자 친화적입니다.

AbiWord는 Microsoft(R) [.filename]#.rtf# 와 같은 일부 독점 형식을 포함하여 다양한 파일 형식을 가져오거나 내보낼 수 있습니다.

AbiWord 패키지를 설치하려면:

[source, shell]
....
# pkg install abiword
....

[[desktop-viewers]]
== 문서 뷰어

UNIX(R)의 등장 이후 일부 새로운 문서 형식이 인기를 얻고 있으며, 이러한 형식에 필요한 뷰어가 기본 시스템에서 제공되지 않을 수 있습니다. 이 섹션에서는 다음 문서 뷰어를 설치하는 방법을 설명합니다:

.지원되는 문서 뷰어
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Okular
| GPL 2.0
| package:graphics/okular[]
| Heavy

| Evince
| GPL 2.0
| package:graphics/evince[]
| Medium

| ePDFView
| GPL 2.0
| package:graphics/epdfview[]
| Medium

| Xpdf
| GPL 2.0
| package:graphics/xpdf[]
| light

|===

[[okular]]
=== Okular

Okular는 범용 문서 뷰어로, KDE Plasma 프로젝트의 일부입니다.

Okular는 뛰어난 기능에 PDF, Postscript, DjVu, CHM, XPS, ePub 등 다양한 종류의 문서를 지원하는 다재다능함을 가지고 있습니다.

Okular를 설치하려면:

[source, shell]
....
# pkg install okular
....

[[evince]]
=== Evince

Evince는 PDF와 포스트스크립트를 포함한 여러 문서 형식을 지원하는 문서 뷰어입니다. GNOME 프로젝트의 일부입니다. Evince의 목표는 ggv, gpdf와 같은 문서 뷰어를 하나의 간단한 애플리케이션으로 대체하는 것입니다.

Evince를 설치하려면:

[source, shell]
....
# pkg install evince
....

[[epdfview]]
=== ePDFView

ePDFView는 Gtk+ 및 Poppler 라이브러리만 사용하는 경량 PDF 문서 뷰어입니다. ePDFView의 목적은 Evince와 유사하지만 GNOME 라이브러리를 사용하지 않는 간단한 PDF 문서 뷰어를 만드는 것입니다.

ePDFView를 설치하려면:

[source, shell]
....
# pkg install epdfview
....

[[xpdf]]
=== Xpdf

작은 FreeBSD PDF 뷰어를 선호하는 사용자를 위해, Xpdf는 리소스를 거의 필요로 하지 않는 가볍고 효율적인 뷰어를 제공합니다. 표준 X 글꼴을 사용하며 추가 툴킷이 필요하지 않습니다.

Xpdf를 설치하려면:

[source, shell]
....
# pkg install xpdf
....

[[desktop-finance]]
== 재무

FreeBSD 데스크탑에서 개인 재무를 관리하기 위해 강력하고 사용하기 쉬운 몇 가지 애플리케이션을 설치할 수 있습니다. 일부는 Quicken 및 Excel에서 사용하는 형식과 같이 널리 사용되는 파일 형식과 호환됩니다.

이 섹션에서는 이러한 프로그램을 다룹니다:

.지원되는 재무 프로그램
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| KMyMoney
| GPL 2.0
| package:finance/kmymoney[]
| Heavy

| GnuCash
| GPL 2.0 and GPL 3.0
| package:finance/gnucash[]
| Heavy

|===

[[kmymoney]]
=== KMyMoney

KMyMoney는 KDE 커뮤니티에서 만든 개인 재무 애플리케이션입니다. KMyMoney는 상용 개인 재무 관리자 애플리케이션에서 볼 수 있는 중요한 기능을 제공하는 것을 목표로 합니다. 또한 사용 편의성과 적절한 이중 입력 회계 기능을 강조합니다. KMyMoney는 표준 Quicken QIF 파일에서 가져오고, 투자를 추적하고, 여러 통화를 처리하며, 다양한 보고서를 제공합니다.

KMyMoney를 설치하려면:

[source, shell]
....
# pkg install kmymoney
....

[[gnucash]]
=== GnuCash

GnuCash는 사용자 친화적이면서도 강력한 애플리케이션을 최종 사용자에게 제공하기 위한 GNOME의 노력의 일환입니다. GnuCash는 수입과 지출, 은행 계좌, 주식을 추적하는 데 사용할 수 있습니다. 전문성을 유지하면서도 직관적인 인터페이스가 특징입니다.

GnuCash는 스마트 레지스터, 계층적 계정 시스템, 다양한 키보드 가속기 및 자동 완성 방법을 제공합니다. 단일 트랜잭션을 여러 개의 세부 트랜잭션으로 분할할 수 있습니다. GnuCash는 Quicken QIF 파일을 가져오고 병합할 수 있습니다. 또한 대부분의 국제 날짜 및 통화 형식을 처리합니다.

GnuCash 설치하려면:

[source, shell]
....
# pkg install gnucash
....
